import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pos_erp/shared/theme/app_theme.dart';
import '../../data/models/customer_model.dart';
import '../providers/customer_provider.dart';


class CustomerFormPage extends ConsumerStatefulWidget {
  final CustomerModel? customer;

  const CustomerFormPage({super.key, this.customer});

  @override
  ConsumerState<CustomerFormPage> createState() => _CustomerFormPageState();
}

class _CustomerFormPageState extends ConsumerState<CustomerFormPage> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _customerCodeController;
  late final TextEditingController _customerNameController;
  late final TextEditingController _addressController;
  late final TextEditingController _phoneController;
  late final TextEditingController _emailController;
  late final TextEditingController _taxIdController;
  late final TextEditingController _creditLimitController;
  late final TextEditingController _creditDaysController;
  late final TextEditingController _memberNoController;

  bool _isLoading        = false;
  bool _codeAutoGenerated = false; // ติดตามว่ารหัสถูก generate อัตโนมัติ
  int  _priceLevel       = 1;     // ระดับราคา 1-5
  bool _isActive         = true;  // สถานะการใช้งาน

  @override
  void initState() {
    super.initState();
    final c = widget.customer;
    _customerCodeController = TextEditingController(text: c?.customerCode ?? '');
    _customerNameController = TextEditingController(text: c?.customerName ?? '');
    _addressController      = TextEditingController(text: c?.address ?? '');
    _phoneController        = TextEditingController(text: c?.phone ?? '');
    _emailController        = TextEditingController(text: c?.email ?? '');
    _taxIdController        = TextEditingController(text: c?.taxId ?? '');
    _creditLimitController  =
        TextEditingController(text: c?.creditLimit.toString() ?? '0');
    _creditDaysController   =
        TextEditingController(text: c?.creditDays.toString() ?? '0');
    _memberNoController     = TextEditingController(text: c?.memberNo ?? '');

    // ✅ โหลด priceLevel และ isActive จากข้อมูลเดิม (ถ้ามี)
    _priceLevel = c?.priceLevel ?? 1;
    _isActive   = c?.isActive   ?? true;

    // สร้างรหัสอัตโนมัติเมื่อเพิ่มใหม่ + ยังไม่มีรหัส
    if (widget.customer == null && _customerCodeController.text.isEmpty) {
      _customerCodeController.text = _generateCode();
      _codeAutoGenerated = true;
    }

    // 🆕 Listener: ให้ปุ่ม "ใช้เบอร์โทร" โผล่/หายแบบ reactive
    _phoneController.addListener(() => setState(() {}));
  }

  // ── สร้างรหัสลูกค้าอัตโนมัติ เช่น CUS-250321-001 ──────────────
  String _generateCode() {
    final now  = DateTime.now();
    final date = '${now.year.toString().substring(2)}'
        '${now.month.toString().padLeft(2, '0')}'
        '${now.day.toString().padLeft(2, '0')}';
    final seq  = (now.millisecondsSinceEpoch % 1000).toString().padLeft(3, '0');
    return 'CUS-$date-$seq';
  }

  void _autoGenerateCode() {
    setState(() {
      _customerCodeController.text = _generateCode();
      _codeAutoGenerated = true;
    });
  }

  @override
  void dispose() {
    _customerCodeController.dispose();
    _customerNameController.dispose();
    _addressController.dispose();
    _phoneController.dispose();
    _emailController.dispose();
    _taxIdController.dispose();
    _creditLimitController.dispose();
    _creditDaysController.dispose();
    _memberNoController.dispose();
    super.dispose();
  }

  Future<void> _handleSave() async {
    if (!_formKey.currentState!.validate()) return;

    // ✅ ตรวจสอบเลขที่สมาชิกเมื่อเลือกระดับราคา > 1
    if (_priceLevel > 1 && _memberNoController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Row(
            children: [
              const Icon(Icons.warning_amber_rounded,
                  color: Colors.white, size: 18),
              const SizedBox(width: 8),
              Text(
                'ระดับราคา Level $_priceLevel '
                'ต้องระบุเลขที่สมาชิกด้วย',
              ),
            ],
          ),
          backgroundColor: Colors.orange[700],
          behavior: SnackBarBehavior.floating,
        ),
      );
      return; // หยุดบันทึก
    }

    setState(() => _isLoading = true);

    String? nul(String v) => v.trim().isEmpty ? null : v.trim();

    final data = {
      'customer_code': _customerCodeController.text.trim(),
      'customer_name': _customerNameController.text.trim(),
      'address': nul(_addressController.text),
      'phone': nul(_phoneController.text),
      'email': nul(_emailController.text),
      'tax_id': nul(_taxIdController.text),
      'credit_limit': double.tryParse(_creditLimitController.text) ?? 0,
      'credit_days': int.tryParse(_creditDaysController.text) ?? 0,
      'member_no': nul(_memberNoController.text),
      // ✅ ส่ง price_level ให้ server หา customer_group_id ที่ตรงกัน
      'price_level': _priceLevel,
      'is_active': _isActive,
      // ✅ ไม่ต้องส่ง customer_group_id เพราะ server จะ lookup จาก price_level
    };

    final bool success;
    if (widget.customer == null) {
      success =
          await ref.read(customerListProvider.notifier).createCustomer(data);
    } else {
      success = await ref
          .read(customerListProvider.notifier)
          .updateCustomer(widget.customer!.customerId, data);
    }

    setState(() => _isLoading = false);

    if (mounted) {
      if (success) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(widget.customer == null
              ? 'เพิ่มลูกค้าสำเร็จ'
              : 'แก้ไขลูกค้าสำเร็จ'),
          backgroundColor: Colors.green,
        ));
      } else {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
          content: Text('เกิดข้อผิดพลาด กรุณาลองใหม่'),
          backgroundColor: Colors.red,
        ));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEdit = widget.customer != null;
    final isDialog = Navigator.of(context).canPop();

    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: isDark ? AppTheme.darkBg : const Color(0xFFF5F5F5),
      body: Column(
        children: [
          // ── Title Bar ─────────────────────────────────────────
          Container(
            color: isDark ? AppTheme.darkTopBar : Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: AppTheme.primaryLight,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(Icons.person_add, color: AppTheme.primary, size: 20),
                ),
                const SizedBox(width: 12),
                Text(
                  isEdit ? 'แก้ไขลูกค้า' : 'เพิ่มลูกค้า',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: isDark ? Colors.white : const Color(0xFF1A1A1A),
                  ),
                ),
                const Spacer(),
                if (isDialog)
                  InkWell(
                    onTap: () => Navigator.pop(context),
                    borderRadius: BorderRadius.circular(6),
                    child: const Padding(
                      padding: EdgeInsets.all(4),
                      child: Icon(Icons.close, size: 20, color: AppTheme.textSub),
                    ),
                  ),
              ],
            ),
          ),

          // ── Form Body ─────────────────────────────────────────
          Expanded(
            child: Form(
              key: _formKey,
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(20),
                child: Column(
                  children: [
                    // ── Responsive: Row 3 col (wide) / Column (narrow)
                    LayoutBuilder(builder: (ctx, bc) {
                      final isWide = bc.maxWidth >= 880;
                      final c1 = _SectionCard(
                              icon: Icons.person_outline,
                              iconColor: AppTheme.primary,
                              title: 'ข้อมูลพื้นฐาน',
                              child: Column(
                                children: [
                                  // ── รหัสลูกค้า + auto-generate ──────────
                                  _CustomerCodeField(
                                    controller: _customerCodeController,
                                    isEdit: isEdit,
                                    isAutoGenerated: _codeAutoGenerated,
                                    enabled: !_isLoading,
                                    onAutoGenerate: _autoGenerateCode,
                                    onManualEdit: () => setState(
                                        () => _codeAutoGenerated = false),
                                  ),
                                  const SizedBox(height: 14),
                                  _FormField(
                                    controller: _customerNameController,
                                    label: 'ชื่อลูกค้า',
                                    icon: Icons.badge_outlined,
                                    required: true,
                                    enabled: !_isLoading,
                                    validator: (v) =>
                                        (v == null || v.isEmpty)
                                            ? 'กรุณากรอกชื่อลูกค้า'
                                            : null,
                                  ),
                                  const SizedBox(height: 14),
                                  _FormField(
                                    controller: _phoneController,
                                    label: 'โทรศัพท์',
                                    icon: Icons.phone_outlined,
                                    keyboardType: TextInputType.phone,
                                    enabled: !_isLoading,
                                    helperText: 'จะถูกเข้ารหัสก่อนบันทึก',
                                  ),
                                  const SizedBox(height: 14),
                                  _FormField(
                                    controller: _emailController,
                                    label: 'อีเมล',
                                    icon: Icons.email_outlined,
                                    keyboardType: TextInputType.emailAddress,
                                    enabled: !_isLoading,
                                  ),
                                  const SizedBox(height: 14),
                                  _FormField(
                                    controller: _taxIdController,
                                    label: 'เลขประจำตัวผู้เสียภาษี',
                                    icon: Icons.receipt_long_outlined,
                                    enabled: !_isLoading,
                                  ),
                                  const SizedBox(height: 14),
                                  _FormField(
                                    controller: _addressController,
                                    label: 'ที่อยู่',
                                    icon: Icons.home_outlined,
                                    maxLines: 3,
                                    enabled: !_isLoading,
                                  ),
                                  if (isEdit) ...[
                                    const SizedBox(height: 14),
                                    _ActiveToggle(
                                      value: _isActive,
                                      enabled: !_isLoading,
                                      onChanged: (v) =>
                                          setState(() => _isActive = v),
                                    ),
                                  ],
                                ],
                              ),
                            );
                      final c2 = _SectionCard(
                              icon: Icons.account_balance_wallet_outlined,
                              iconColor: const Color(0xFF1565C0),
                              title: 'วงเงินเครดิต',
                              child: Column(
                                children: [
                                  _FormField(
                                    controller: _creditLimitController,
                                    label: 'วงเงินเครดิต (฿)',
                                    icon: Icons.monetization_on_outlined,
                                    keyboardType: TextInputType.number,
                                    enabled: !_isLoading,
                                  ),
                                  const SizedBox(height: 14),
                                  _FormField(
                                    controller: _creditDaysController,
                                    label: 'ระยะเวลาเครดิต (วัน)',
                                    icon: Icons.calendar_today_outlined,
                                    keyboardType: TextInputType.number,
                                    enabled: !_isLoading,
                                  ),
                                  const SizedBox(height: 14),
                                  // Info box
                                  Container(
                                    padding: const EdgeInsets.all(12),
                                    decoration: BoxDecoration(
                                      color: const Color(0xFFE3F2FD),
                                      borderRadius: BorderRadius.circular(8),
                                      border: Border.all(
                                          color: const Color(0xFF90CAF9)),
                                    ),
                                    child: const Row(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      children: [
                                        Icon(Icons.info_outline,
                                            size: 16,
                                            color: Color(0xFF1565C0)),
                                        SizedBox(width: 8),
                                        Expanded(
                                          child: Text(
                                            'วงเงินเครดิตจะถูกตรวจสอบอัตโนมัติเมื่อสร้างใบแจ้งหนี้ AR',
                                            style: TextStyle(
                                              fontSize: 12,
                                              color: Color(0xFF1565C0),
                                              height: 1.4,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            );
                      final c3 = _SectionCard(
                              icon: Icons.card_membership_outlined,
                              iconColor: const Color(0xFFFFB300),
                              title: 'ข้อมูลสมาชิก',
                              child: Column(
                                children: [
                                  // ── เลขที่สมาชิก + ปุ่ม "ใช้เบอร์โทร" ──
                                  _MemberNoField(
                                    memberNoController: _memberNoController,
                                    phoneText: _phoneController.text,
                                    enabled: !_isLoading,
                                    isDark: isDark,
                                    onUsePhone: () {
                                      setState(() {
                                        _memberNoController.text =
                                            _phoneController.text
                                                .replaceAll(RegExp(r'[^0-9]'), '');
                                      });
                                    },
                                  ),
                                  const SizedBox(height: 16),

                                  // ── ระดับราคา (Price Level) ──────────
                                  _PriceLevelSelector(
                                    value: _priceLevel,
                                    enabled: !_isLoading,
                                    onChanged: (v) =>
                                        setState(() => _priceLevel = v),
                                  ),
                                  const SizedBox(height: 14),

                                  // คะแนนสะสม (edit mode)
                                  if (isEdit &&
                                      (widget.customer?.points ?? 0) > 0)
                                    Container(
                                      padding: const EdgeInsets.all(12),
                                      decoration: BoxDecoration(
                                        color: const Color(0xFFFFF8E1),
                                        borderRadius: BorderRadius.circular(8),
                                        border: Border.all(
                                            color: const Color(0xFFFFE082)),
                                      ),
                                      child: Row(
                                        children: [
                                          const Icon(Icons.stars,
                                              color: Color(0xFFFFB300),
                                              size: 20),
                                          const SizedBox(width: 10),
                                          Column(
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: [
                                              const Text('คะแนนสะสม',
                                                  style: TextStyle(
                                                      fontSize: 11,
                                                      color: AppTheme.textSub)),
                                              Text(
                                                '${widget.customer!.points} คะแนน',
                                                style: const TextStyle(
                                                  fontSize: 18,
                                                  fontWeight: FontWeight.bold,
                                                  color: Color(0xFFE65100),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ),
                                  const SizedBox(height: 14),
                                  // Info
                                  Container(
                                    padding: const EdgeInsets.all(12),
                                    decoration: BoxDecoration(
                                      color: const Color(0xFFFFF8E1),
                                      borderRadius: BorderRadius.circular(8),
                                      border: Border.all(
                                          color: const Color(0xFFFFE082)),
                                    ),
                                    child: const Row(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      children: [
                                        Icon(Icons.star_outline,
                                            size: 16,
                                            color: Color(0xFFFFB300)),
                                        SizedBox(width: 8),
                                        Expanded(
                                          child: Text(
                                            'ทุก ฿100 ที่ซื้อ จะได้รับ 1 คะแนนสะสมอัตโนมัติ',
                                            style: TextStyle(
                                              fontSize: 12,
                                              color: Color(0xFFE65100),
                                              height: 1.4,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            );
                      if (isWide) {
                        return IntrinsicHeight(
                          child: Row(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Expanded(child: c1),
                              const SizedBox(width: 16),
                              Expanded(child: c2),
                              const SizedBox(width: 16),
                              Expanded(child: c3),
                            ],
                          ),
                        );
                      }
                      return Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          c1, const SizedBox(height: 16),
                          c2, const SizedBox(height: 16),
                          c3,
                        ],
                      );
                    }),
                  ],
                ),
              ),
            ),
          ),

          // ── Bottom Action Bar ─────────────────────────────────
          Container(
            color: isDark ? AppTheme.darkTopBar : Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                OutlinedButton(
                  onPressed: _isLoading ? null : () => Navigator.pop(context),
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 24, vertical: 12),
                    side: const BorderSide(color: AppTheme.border),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8)),
                  ),
                  child: const Text('ยกเลิก',
                      style: TextStyle(color: AppTheme.textSub)),
                ),
                const SizedBox(width: 12),
                ElevatedButton.icon(
                  onPressed: _isLoading ? null : _handleSave,
                  icon: _isLoading
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                              strokeWidth: 2, color: Colors.white),
                        )
                      : const Icon(Icons.save_outlined, size: 18),
                  label: Text(isEdit ? 'บันทึก' : 'เพิ่มลูกค้า',
                      style: const TextStyle(fontSize: 14)),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppTheme.primary,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(
                        horizontal: 24, vertical: 12),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8)),
                    elevation: 0,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Section Card
// ─────────────────────────────────────────────────────────────────
class _SectionCard extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final String title;
  final Widget child;

  const _SectionCard({
    required this.icon,
    required this.iconColor,
    required this.title,
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      decoration: BoxDecoration(
        color: isDark ? AppTheme.darkCard : Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
            color: isDark ? Colors.white12 : AppTheme.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Section Header
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: BoxDecoration(
              color: isDark ? AppTheme.darkElement : AppTheme.headerBg,
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(12),
                topRight: Radius.circular(12),
              ),
              border: Border(
                  bottom: BorderSide(
                      color: isDark ? Colors.white12 : AppTheme.border)),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(6),
                  decoration: BoxDecoration(
                    color: iconColor.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: Icon(icon, size: 15, color: iconColor),
                ),
                const SizedBox(width: 8),
                Text(
                  title,
                  style: TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.w600,
                    color: iconColor,
                  ),
                ),
              ],
            ),
          ),
          // Content
          Padding(
            padding: const EdgeInsets.all(16),
            child: child,
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Form Field
// ─────────────────────────────────────────────────────────────────
class _FormField extends StatelessWidget {
  final TextEditingController controller;
  final String label;
  final IconData icon;
  final bool required;
  final bool enabled;
  final TextInputType? keyboardType;
  final int maxLines;
  final String? helperText;
  final String? Function(String?)? validator;

  const _FormField({
    required this.controller,
    required this.label,
    required this.icon,
    this.required = false,
    this.enabled = true,
    this.keyboardType,
    this.maxLines = 1,
    this.helperText,
    this.validator,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return TextFormField(
      controller: controller,
      enabled: enabled,
      keyboardType: keyboardType,
      maxLines: maxLines,
      validator: validator,
      style: TextStyle(
        fontSize: 13,
        color: isDark ? Colors.white : Colors.black87,
      ),
      decoration: InputDecoration(
        labelText: required ? '$label *' : label,
        labelStyle: TextStyle(fontSize: 13, color: isDark ? Colors.white60 : AppTheme.textSub),
        helperText: helperText,
        helperStyle: TextStyle(fontSize: 11, color: isDark ? Colors.white54 : AppTheme.textSub),
        prefixIcon: Icon(icon, size: 17, color: isDark ? Colors.white54 : AppTheme.textSub),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: isDark ? Colors.white24 : AppTheme.border),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: isDark ? Colors.white24 : AppTheme.border),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: AppTheme.primary, width: 1.5),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Colors.red),
        ),
        filled: true,
        fillColor: enabled
            ? (isDark ? AppTheme.darkElement : Colors.white)
            : (isDark ? AppTheme.darkCard : const Color(0xFFF5F5F5)),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// _CustomerCodeField — รหัสลูกค้า + ปุ่ม auto-generate
// ─────────────────────────────────────────────────────────────────
class _CustomerCodeField extends StatelessWidget {
  final TextEditingController controller;
  final bool isEdit;
  final bool isAutoGenerated;
  final bool enabled;
  final VoidCallback onAutoGenerate;
  final VoidCallback onManualEdit;

  const _CustomerCodeField({
    required this.controller,
    required this.isEdit,
    required this.isAutoGenerated,
    required this.enabled,
    required this.onAutoGenerate,
    required this.onManualEdit,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Label row + badge + ปุ่ม generate
        Row(
          children: [
            Text('รหัสลูกค้า *',
                style: TextStyle(
                    fontSize: 12,
                    color: isDark ? Colors.white60 : AppTheme.textSub)),
            const SizedBox(width: 6),
            if (isAutoGenerated)
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 7, vertical: 2),
                decoration: BoxDecoration(
                  color: AppTheme.successContainer,
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: const Color(0xFF81C784)),
                ),
                child: const Text('สร้างอัตโนมัติ',
                    style: TextStyle(
                        fontSize: 10,
                        color: AppTheme.success,
                        fontWeight: FontWeight.w600)),
              ),
            const Spacer(),
            // ปุ่ม generate (เฉพาะ create mode)
            if (!isEdit)
              InkWell(
                onTap: onAutoGenerate,
                borderRadius: BorderRadius.circular(6),
                child: Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: AppTheme.primaryLight,
                    borderRadius: BorderRadius.circular(6),
                    border: Border.all(
                        color: AppTheme.primary.withValues(alpha: 0.3)),
                  ),
                  child: const Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.auto_awesome,
                          size: 12, color: AppTheme.primary),
                      SizedBox(width: 4),
                      Text('สร้างรหัส',
                          style: TextStyle(
                              fontSize: 11,
                              color: AppTheme.primary,
                              fontWeight: FontWeight.w500)),
                    ],
                  ),
                ),
              ),
          ],
        ),
        const SizedBox(height: 4),
        // TextField
        TextFormField(
          controller: controller,
          enabled: enabled,
          onChanged: (_) => onManualEdit(),
          validator: (v) =>
              (v == null || v.isEmpty) ? 'กรุณากรอกรหัสลูกค้า' : null,
          style: TextStyle(
              fontSize: 13,
              color: isDark ? Colors.white : Colors.black87),
          decoration: InputDecoration(
            hintText: 'เช่น CUS-250321-001',
            hintStyle: TextStyle(
                fontSize: 12,
                color: isDark ? Colors.white38 : AppTheme.textSub),
            prefixIcon: Icon(Icons.qr_code,
                size: 17,
                color: isDark ? Colors.white54 : AppTheme.textSub),
            contentPadding: const EdgeInsets.symmetric(
                horizontal: 12, vertical: 12),
            border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: BorderSide(
                    color: isDark ? Colors.white24 : AppTheme.border)),
            enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: BorderSide(
                    color: isAutoGenerated
                        ? const Color(0xFF81C784)
                        : (isDark ? Colors.white24 : AppTheme.border))),
            focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(
                    color: AppTheme.primary, width: 1.5)),
            errorBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: Colors.red)),
            filled: true,
            fillColor: isAutoGenerated
                ? AppTheme.successContainer.withValues(alpha: 0.4)
                : (isDark ? AppTheme.darkElement : Colors.white),
          ),
        ),
        Padding(
          padding: const EdgeInsets.only(top: 4, left: 2),
          child: Text(
            isEdit
                ? 'รหัสลูกค้า (ไม่แนะนำให้เปลี่ยน)'
                : 'ระบบสร้างให้อัตโนมัติ หรือกดปุ่ม "สร้างรหัส" เพื่อ generate ใหม่',
            style: TextStyle(
                fontSize: 10,
                color: isDark ? Colors.white38 : AppTheme.textSub),
          ),
        ),
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// 🆕 _MemberNoField — เลขที่สมาชิก + ปุ่ม "ใช้เบอร์โทร"
// ─────────────────────────────────────────────────────────────────
class _MemberNoField extends StatelessWidget {
  final TextEditingController memberNoController;
  final String phoneText;
  final bool enabled;
  final bool isDark;
  final VoidCallback onUsePhone;

  const _MemberNoField({
    required this.memberNoController,
    required this.phoneText,
    required this.enabled,
    required this.isDark,
    required this.onUsePhone,
  });

  @override
  Widget build(BuildContext context) {
    final hasPhone = phoneText.trim().isNotEmpty;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // ── Label row + ปุ่ม "ใช้เบอร์โทร" ──────────────────────
        Row(
          children: [
            Text(
              'เลขที่สมาชิก',
              style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.w500,
                color: isDark ? Colors.white70 : AppTheme.textSub,
              ),
            ),
            const Spacer(),
            // ปุ่มโผล่เฉพาะเมื่อมีเบอร์โทรแล้ว
            if (hasPhone)
              GestureDetector(
                onTap: enabled ? onUsePhone : null,
                child: Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: isDark
                        ? const Color(0xFF1B5E20).withValues(alpha: 0.4)
                        : const Color(0xFFE8F5E9),
                    borderRadius: BorderRadius.circular(6),
                    border: Border.all(color: const Color(0xFF81C784)),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const Icon(Icons.phone_outlined,
                          size: 12, color: Color(0xFF2E7D32)),
                      const SizedBox(width: 4),
                      Text(
                        'ใช้เบอร์โทร',
                        style: TextStyle(
                          fontSize: 11,
                          color: isDark
                              ? const Color(0xFF81C784)
                              : const Color(0xFF2E7D32),
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
          ],
        ),
        const SizedBox(height: 6),

        // ── TextField ─────────────────────────────────────────────
        TextFormField(
          controller: memberNoController,
          enabled: enabled,
          style: TextStyle(
              fontSize: 13,
              color: isDark ? Colors.white : Colors.black87),
          decoration: InputDecoration(
            hintText: 'เช่น 0812345678',
            hintStyle: TextStyle(
                fontSize: 12,
                color: isDark ? Colors.white38 : AppTheme.textSub),
            prefixIcon: Icon(Icons.badge_outlined,
                size: 17,
                color: isDark ? Colors.white54 : AppTheme.textSub),
            helperText: 'สำหรับสะสมคะแนน',
            helperStyle: TextStyle(
                fontSize: 10,
                color: isDark ? Colors.white38 : AppTheme.textSub),
            contentPadding: const EdgeInsets.symmetric(
                horizontal: 12, vertical: 12),
            border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: BorderSide(
                    color: isDark ? Colors.white24 : AppTheme.border)),
            enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: BorderSide(
                    color: isDark ? Colors.white24 : AppTheme.border)),
            focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(
                    color: AppTheme.primary, width: 1.5)),
            filled: true,
            fillColor: isDark ? AppTheme.darkElement : Colors.white,
          ),
        ),
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// _PriceLevelSelector — เลือกระดับราคา 1-5
// ─────────────────────────────────────────────────────────────────
class _PriceLevelSelector extends StatelessWidget {
  final int value;
  final bool enabled;
  final ValueChanged<int> onChanged;

  const _PriceLevelSelector({
    required this.value,
    required this.enabled,
    required this.onChanged,
  });

  static const _levels = [
    (1, 'Level 1', 'ราคาปกติ (ทั่วไป)',  Color(0xFF1565C0), Color(0xFFE3F2FD)),
    (2, 'Level 2', 'ราคาสมาชิก',         Color(0xFF2E7D32), Color(0xFFE8F5E9)),
    (3, 'Level 3', 'ราคาส่ง',             Color(0xFFE65100), Color(0xFFFFF3E0)),
    (4, 'Level 4', 'ราคาตัวแทน',         Color(0xFF6A1B9A), Color(0xFFF3E5F5)),
    (5, 'Level 5', 'ราคา VIP / พิเศษ',  Color(0xFFC62828), Color(0xFFFFEBEE)),
  ];

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(Icons.sell_outlined,
                size: 15,
                color: isDark ? Colors.white54 : AppTheme.textSub),
            const SizedBox(width: 6),
            Text('ระดับราคา',
                style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w500,
                    color: isDark ? Colors.white70 : AppTheme.textSub)),
          ],
        ),
        const SizedBox(height: 8),
        // ปุ่ม level 1-5 แบบ wrap
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: _levels.map((lvl) {
            final (level, label, desc, color, bgColor) = lvl;
            final isSelected = value == level;
            return GestureDetector(
              onTap: enabled ? () => onChanged(level) : null,
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 150),
                padding: const EdgeInsets.symmetric(
                    horizontal: 12, vertical: 8),
                decoration: BoxDecoration(
                  color: isSelected
                      ? (isDark ? color.withValues(alpha: 0.3) : bgColor)
                      : (isDark ? AppTheme.darkElement : Colors.white),
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(
                    color: isSelected
                        ? color
                        : (isDark ? Colors.white24 : AppTheme.border),
                    width: isSelected ? 1.5 : 1,
                  ),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        if (isSelected)
                          Icon(Icons.check_circle,
                              size: 13, color: color)
                        else
                          Icon(Icons.circle_outlined,
                              size: 13,
                              color: isDark
                                  ? Colors.white38
                                  : AppTheme.textSub),
                        const SizedBox(width: 4),
                        Text(label,
                            style: TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.w600,
                                color: isSelected
                                    ? color
                                    : (isDark
                                        ? Colors.white70
                                        : AppTheme.textSub))),
                      ],
                    ),
                    const SizedBox(height: 2),
                    Text(desc,
                        style: TextStyle(
                            fontSize: 10,
                            color: isSelected
                                ? color.withValues(alpha: 0.8)
                                : (isDark
                                    ? Colors.white38
                                    : AppTheme.textSub))),
                  ],
                ),
              ),
            );
          }).toList(),
        ),
        const SizedBox(height: 6),
        Text(
          'ราคาที่ใช้กับลูกค้ากลุ่มนี้เมื่อขายสินค้า',
          style: TextStyle(
              fontSize: 10,
              color: isDark ? Colors.white38 : AppTheme.textSub),
        ),
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// _ActiveToggle — toggle เปิด/ปิดการใช้งานลูกค้า
// ─────────────────────────────────────────────────────────────────
class _ActiveToggle extends StatelessWidget {
  final bool value;
  final bool enabled;
  final ValueChanged<bool> onChanged;

  const _ActiveToggle({
    required this.value,
    required this.enabled,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
      decoration: BoxDecoration(
        color: value
            ? const Color(0xFFE8F5E9)
            : (isDark ? Colors.white10 : const Color(0xFFFAFAFA)),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(
          color: value ? const Color(0xFFA5D6A7) : AppTheme.border,
        ),
      ),
      child: Row(
        children: [
          Icon(
            value ? Icons.check_circle_outline : Icons.cancel_outlined,
            size: 18,
            color: value ? AppTheme.successColor : AppTheme.textSub,
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'สถานะลูกค้า',
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w500,
                    color: isDark ? Colors.white70 : AppTheme.textSub,
                  ),
                ),
                Text(
                  value ? 'ใช้งานอยู่' : 'ปิดการใช้งาน',
                  style: TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.w600,
                    color: value ? AppTheme.successColor : AppTheme.textSub,
                  ),
                ),
              ],
            ),
          ),
          Switch(
            value: value,
            onChanged: enabled ? onChanged : null,
            activeThumbColor: AppTheme.successColor,
          ),
        ],
      ),
    );
  }
}