// lib/features/products/presentation/pages/barcode_generator_page.dart
//
// สร้างและพิมพ์บาร์โค้ดสินค้าหลายรายการในหน้าเดียว — พิมพ์ A4 แนวตั้ง

import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:printing/printing.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../../../shared/pdf/barcode_pdf_builder.dart';
import '../../../../shared/pdf/pdf_preview_dialog.dart';
import '../../../../shared/theme/app_theme.dart';
import '../../data/models/product_model.dart';
import '../providers/product_provider.dart';

class _BarcodeItem {
  final String id;
  final String name;
  final String barcodeValue;
  final int qty;
  final bool autoGenerated;

  const _BarcodeItem({
    required this.id,
    required this.name,
    required this.barcodeValue,
    this.qty = 1,
    this.autoGenerated = false,
  });

  _BarcodeItem copyWith({
    String? name,
    String? barcodeValue,
    int? qty,
    bool? autoGenerated,
  }) => _BarcodeItem(
    id: id,
    name: name ?? this.name,
    barcodeValue: barcodeValue ?? this.barcodeValue,
    qty: qty ?? this.qty,
    autoGenerated: autoGenerated ?? this.autoGenerated,
  );
}

class _BarcodeHistoryEntry {
  final String barcodeValue;
  final String name;
  final String type;
  final String updatedAt;

  const _BarcodeHistoryEntry({
    required this.barcodeValue,
    required this.name,
    required this.type,
    required this.updatedAt,
  });

  factory _BarcodeHistoryEntry.fromJson(Map<String, dynamic> json) =>
      _BarcodeHistoryEntry(
        barcodeValue: json['barcodeValue'] as String? ?? '',
        name: json['name'] as String? ?? '',
        type: json['type'] as String? ?? 'code128',
        updatedAt: json['updatedAt'] as String? ?? '',
      );

  Map<String, dynamic> toJson() => {
    'barcodeValue': barcodeValue,
    'name': name,
    'type': type,
    'updatedAt': updatedAt,
  };
}

class BarcodeGeneratorPage extends ConsumerStatefulWidget {
  const BarcodeGeneratorPage({super.key});

  @override
  ConsumerState<BarcodeGeneratorPage> createState() =>
      _BarcodeGeneratorPageState();
}

class _BarcodeGeneratorPageState extends ConsumerState<BarcodeGeneratorPage> {
  static const _historyPrefsKey = 'barcode_generator_history_v1';
  static const _historyLimit = 20;

  final List<_BarcodeItem> _items = [];
  List<_BarcodeHistoryEntry> _history = const [];

  BarcodePdfType _type = BarcodePdfType.code128;
  int _columnsPerRow = 3;
  bool _isPrinting = false;
  bool _isPreviewing = false;
  bool _isSharing = false;
  bool _isHistoryLoading = true;
  String? _selectedItemId;
  String _historyQuery = '';

  int get _totalSlips => _items.fold(0, (s, i) => s + i.qty);

  @override
  void initState() {
    super.initState();
    _loadHistory();
  }

  Future<void> _loadHistory() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_historyPrefsKey);
    if (raw == null || raw.isEmpty) {
      if (!mounted) return;
      setState(() => _isHistoryLoading = false);
      return;
    }

    try {
      final decoded = jsonDecode(raw) as List<dynamic>;
      final entries = decoded
          .whereType<Map>()
          .map(
            (e) => _BarcodeHistoryEntry.fromJson(Map<String, dynamic>.from(e)),
          )
          .where(
            (e) => e.barcodeValue.trim().isNotEmpty && e.name.trim().isNotEmpty,
          )
          .toList();
      if (!mounted) return;
      setState(() {
        _history = entries;
        _isHistoryLoading = false;
      });
    } catch (_) {
      if (!mounted) return;
      setState(() => _isHistoryLoading = false);
    }
  }

  Future<void> _persistHistory() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(
      _historyPrefsKey,
      jsonEncode(_history.map((e) => e.toJson()).toList()),
    );
  }

  Future<void> _saveHistoryEntry({
    required String barcodeValue,
    String name = '',
    BarcodePdfType? type,
  }) async {
    final barcode = barcodeValue.trim();
    final trimmedName = name.trim();
    if (barcode.isEmpty || trimmedName.isEmpty) return;

    final entry = _BarcodeHistoryEntry(
      barcodeValue: barcode,
      name: trimmedName,
      type: _barcodeTypeKey(type ?? _type),
      updatedAt: DateTime.now().toIso8601String(),
    );

    final next = [
      entry,
      ..._history.where((e) => e.barcodeValue != barcode),
    ].take(_historyLimit).toList();

    if (!mounted) return;
    setState(() => _history = next);
    await _persistHistory();
  }

  Future<void> _removeHistoryEntry(String barcodeValue) async {
    setState(() {
      _history = _history.where((e) => e.barcodeValue != barcodeValue).toList();
    });
    await _persistHistory();
  }

  Future<void> _clearHistory() async {
    setState(() => _history = const []);
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_historyPrefsKey);
  }

  Future<void> _persistCurrentItemsToHistory() async {
    for (final item in _items) {
      await _saveHistoryEntry(barcodeValue: item.barcodeValue, name: item.name);
    }
  }

  List<_BarcodeHistoryEntry> get _filteredHistory {
    final q = _historyQuery.trim().toLowerCase();
    if (q.isEmpty) return _history;
    return _history.where((entry) {
      return entry.name.toLowerCase().contains(q) ||
          entry.barcodeValue.toLowerCase().contains(q) ||
          entry.type.toLowerCase().contains(q);
    }).toList();
  }

  void _addItem({
    String name = '',
    String? barcode,
    bool autoGenerated = true,
  }) {
    final nextBarcode = barcode?.trim().isNotEmpty == true
        ? barcode!.trim()
        : _generateBarcode();
    setState(() {
      final item = _BarcodeItem(
        id: UniqueKey().toString(),
        name: name,
        barcodeValue: nextBarcode,
        autoGenerated: barcode?.trim().isEmpty ?? true ? autoGenerated : false,
      );
      _items.insert(0, item);
      _selectedItemId = item.id;
    });
    unawaited(_saveHistoryEntry(barcodeValue: nextBarcode, name: name));
  }

  void _addFromProduct(ProductModel p) {
    final productBarcode = (p.barcode?.trim().isNotEmpty ?? false)
        ? p.barcode!.trim()
        : _generateBarcode();
    _addItem(
      name: p.productName,
      barcode: productBarcode,
      autoGenerated: p.barcode?.trim().isEmpty ?? true,
    );
  }

  void _addFromHistory(_BarcodeHistoryEntry entry) {
    final duplicateIndex = _items.indexWhere(
      (item) => item.barcodeValue.trim() == entry.barcodeValue.trim(),
    );
    if (duplicateIndex >= 0) {
      _selectItem(_items[duplicateIndex].id);
      _snack('บาร์โค้ดนี้มีอยู่ในรายการแล้ว', error: true);
      return;
    }

    _addItem(
      name: entry.name,
      barcode: entry.barcodeValue,
      autoGenerated: false,
    );
  }

  void _removeItem(String id) => setState(() {
    _items.removeWhere((i) => i.id == id);
    if (_selectedItemId == id) {
      _selectedItemId = _items.isNotEmpty ? _items.first.id : null;
    }
  });

  void _selectItem(String id) {
    if (_selectedItemId == id) return;
    setState(() => _selectedItemId = id);
  }

  void _updateItem(
    String id, {
    String? name,
    String? barcodeValue,
    int? qty,
    bool? autoGenerated,
  }) {
    setState(() {
      final idx = _items.indexWhere((i) => i.id == id);
      if (idx < 0) return;
      _items[idx] = _items[idx].copyWith(
        name: name,
        barcodeValue: barcodeValue,
        qty: qty,
        autoGenerated: autoGenerated,
      );
    });

    final updated = _items.firstWhere((i) => i.id == id);
    if (updated.barcodeValue.trim().isNotEmpty &&
        (barcodeValue != null || name != null)) {
      unawaited(
        _saveHistoryEntry(
          barcodeValue: updated.barcodeValue.trim(),
          name: updated.name,
        ),
      );
    }
  }

  void _regenerateBarcode(String id) {
    final next = _generateBarcode();
    _updateItem(id, barcodeValue: next, autoGenerated: true);
  }

  void _handleTypeChanged(BarcodePdfType type) {
    setState(() {
      _type = type;
      _items.replaceRange(
        0,
        _items.length,
        _items.map((item) {
          if (!item.autoGenerated) return item;
          return item.copyWith(
            barcodeValue: _generateBarcode(),
            autoGenerated: true,
          );
        }),
      );
    });
  }

  String? _validateItems() {
    if (_items.isEmpty) return 'ยังไม่มีสินค้าในรายการ';
    final invalid = _items
        .where((i) => i.name.trim().isEmpty || i.barcodeValue.trim().isEmpty)
        .toList();
    if (invalid.isNotEmpty) return 'กรุณากรอกชื่อสินค้าและค่าบาร์โค้ดให้ครบ';
    if (_type == BarcodePdfType.ean13) {
      final bad = _items
          .where((i) => !RegExp(r'^\d{12,13}$').hasMatch(i.barcodeValue.trim()))
          .toList();
      if (bad.isNotEmpty) {
        return 'EAN-13 ต้องเป็นตัวเลข 12–13 หลัก (${bad.first.name.isEmpty ? bad.first.barcodeValue : bad.first.name})';
      }
    }
    return null;
  }

  List<BarcodeLabel> _buildLabels() => _items
      .expand(
        (item) => BarcodePdfBuilder.expand(
          BarcodeLabel(
            name: item.name.trim(),
            barcodeValue: item.barcodeValue.trim(),
          ),
          item.qty,
        ),
      )
      .toList();

  Future<void> _preview() async {
    final err = _validateItems();
    if (err != null) {
      _snack(err, error: true);
      return;
    }

    setState(() => _isPreviewing = true);
    try {
      await _persistCurrentItemsToHistory();
      final doc = await BarcodePdfBuilder.build(
        _buildLabels(),
        columnsPerRow: _columnsPerRow,
        type: _type,
      );
      final bytes = await doc.save();
      if (!mounted) return;
      await showDialog<void>(
        context: context,
        builder: (_) => PdfPreviewDialog(
          bytes: bytes,
          title: 'ตัวอย่างบาร์โค้ด',
          filename: 'barcodes_${DateTime.now().millisecondsSinceEpoch}.pdf',
        ),
      );
    } catch (e) {
      if (mounted) _snack('สร้าง PDF ไม่สำเร็จ: $e', error: true);
    } finally {
      if (mounted) setState(() => _isPreviewing = false);
    }
  }

  Future<void> _print() async {
    final err = _validateItems();
    if (err != null) {
      _snack(err, error: true);
      return;
    }

    setState(() => _isPrinting = true);
    try {
      await _persistCurrentItemsToHistory();
      final labels = _buildLabels();
      await Printing.layoutPdf(
        onLayout: (_) async {
          final doc = await BarcodePdfBuilder.build(
            labels,
            columnsPerRow: _columnsPerRow,
            type: _type,
          );
          return doc.save();
        },
        name: 'barcodes_${DateTime.now().millisecondsSinceEpoch}',
      );
    } catch (e) {
      if (mounted) _snack('พิมพ์ไม่สำเร็จ: $e', error: true);
    } finally {
      if (mounted) setState(() => _isPrinting = false);
    }
  }

  Future<void> _share() async {
    final err = _validateItems();
    if (err != null) {
      _snack(err, error: true);
      return;
    }

    setState(() => _isSharing = true);
    try {
      await _persistCurrentItemsToHistory();
      final doc = await BarcodePdfBuilder.build(
        _buildLabels(),
        columnsPerRow: _columnsPerRow,
        type: _type,
      );
      final bytes = await doc.save();
      await Printing.sharePdf(
        bytes: bytes,
        filename: 'barcodes_${DateTime.now().millisecondsSinceEpoch}.pdf',
      );
    } catch (e) {
      if (mounted) _snack('แชร์ไม่สำเร็จ: $e', error: true);
    } finally {
      if (mounted) setState(() => _isSharing = false);
    }
  }

  String _generateBarcode() {
    final now = DateTime.now();
    final base =
        '${now.year.toString().substring(2)}'
        '${now.month.toString().padLeft(2, '0')}'
        '${now.day.toString().padLeft(2, '0')}'
        '${now.hour.toString().padLeft(2, '0')}'
        '${now.minute.toString().padLeft(2, '0')}'
        '${now.second.toString().padLeft(2, '0')}';
    final millis = (now.millisecond + _items.length).toString().padLeft(3, '0');
    final body12 = '$base$millis'.substring(0, 12);
    return '$body12${_ean13CheckDigit(body12)}';
  }

  int _ean13CheckDigit(String body12) {
    final digits = body12.split('').map(int.parse).toList();
    int sum = 0;
    for (int i = 0; i < digits.length; i++) {
      sum += digits[i] * (i.isEven ? 1 : 3);
    }
    return (10 - (sum % 10)) % 10;
  }

  String _barcodeTypeKey(BarcodePdfType type) {
    switch (type) {
      case BarcodePdfType.code128:
        return 'code128';
      case BarcodePdfType.ean13:
        return 'ean13';
      case BarcodePdfType.qrCode:
        return 'qrcode';
    }
  }

  void _snack(String msg, {bool error = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(msg),
        behavior: SnackBarBehavior.floating,
        backgroundColor: error ? AppTheme.error : AppTheme.success,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final products = ref.watch(productListProvider).value ?? [];
    final colors = _BarcodePageColors.of(context);
    final isWide = MediaQuery.of(context).size.width >= 1100;

    return Scaffold(
      backgroundColor: colors.scaffoldBg,
      body: Column(
        children: [
          _BarcodeTopBar(
            colors: colors,
            totalSlips: _totalSlips,
            totalItems: _items.length,
            isPrinting: _isPrinting,
            onPrint: _items.isEmpty ? null : _print,
          ),
          _BarcodeSummaryBar(
            colors: colors,
            totalItems: _items.length,
            totalSlips: _totalSlips,
            historyCount: _history.length,
            typeLabel: _type.label,
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 0),
              child: isWide
                  ? Row(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        Expanded(
                          flex: 7,
                          child: _BarcodeMainPanel(
                            colors: colors,
                            type: _type,
                            columnsPerRow: _columnsPerRow,
                            onTypeChanged: _handleTypeChanged,
                            onColumnsChanged: (c) =>
                                setState(() => _columnsPerRow = c),
                            child: _buildItemsList(colors),
                          ),
                        ),
                        const SizedBox(width: 16),
                        SizedBox(
                          width: 320,
                          child: _BarcodeHistoryPanel(
                            colors: colors,
                            entries: _filteredHistory,
                            query: _historyQuery,
                            isLoading: _isHistoryLoading,
                            onQueryChanged: (value) =>
                                setState(() => _historyQuery = value),
                            onUse: _addFromHistory,
                            onRemove: _removeHistoryEntry,
                            onClear: _clearHistory,
                          ),
                        ),
                      ],
                    )
                  : Column(
                      children: [
                        Expanded(
                          flex: 6,
                          child: _BarcodeMainPanel(
                            colors: colors,
                            type: _type,
                            columnsPerRow: _columnsPerRow,
                            onTypeChanged: _handleTypeChanged,
                            onColumnsChanged: (c) =>
                                setState(() => _columnsPerRow = c),
                            child: _buildItemsList(colors),
                          ),
                        ),
                        const SizedBox(height: 12),
                        Expanded(
                          flex: 4,
                          child: _BarcodeHistoryPanel(
                            colors: colors,
                            entries: _filteredHistory,
                            query: _historyQuery,
                            isLoading: _isHistoryLoading,
                            onQueryChanged: (value) =>
                                setState(() => _historyQuery = value),
                            onUse: _addFromHistory,
                            onRemove: _removeHistoryEntry,
                            onClear: _clearHistory,
                          ),
                        ),
                      ],
                    ),
            ),
          ),
        ],
      ),
      bottomNavigationBar: _BottomBar(
        colors: colors,
        products: products,
        isPreviewing: _isPreviewing,
        isSharing: _isSharing,
        hasItems: _items.isNotEmpty,
        onAddManual: () => _addItem(),
        onAddFromProduct: _addFromProduct,
        onPreview: _preview,
        onShare: _share,
      ),
    );
  }

  Widget _buildItemsList(_BarcodePageColors colors) {
    if (_items.isEmpty) {
      return _EmptyState(colors: colors, onAdd: () => _addItem());
    }

    return ListView.separated(
      padding: const EdgeInsets.all(16),
      itemCount: _items.length,
      separatorBuilder: (_, _) => const SizedBox(height: 10),
      itemBuilder: (_, i) => _ItemRow(
        item: _items[i],
        colors: colors,
        isSelected: _selectedItemId == _items[i].id,
        onActivate: () => _selectItem(_items[i].id),
        onRemove: () => _removeItem(_items[i].id),
        onNameChanged: (v) => _updateItem(_items[i].id, name: v),
        onBarcodeChanged: (v) =>
            _updateItem(_items[i].id, barcodeValue: v, autoGenerated: false),
        onQtyChanged: (v) => _updateItem(_items[i].id, qty: v),
        onGenerateBarcode: () => _regenerateBarcode(_items[i].id),
      ),
    );
  }
}

class _BarcodeTopBar extends StatelessWidget {
  final _BarcodePageColors colors;
  final int totalSlips;
  final int totalItems;
  final bool isPrinting;
  final VoidCallback? onPrint;

  const _BarcodeTopBar({
    required this.colors,
    required this.totalSlips,
    required this.totalItems,
    required this.isPrinting,
    required this.onPrint,
  });

  @override
  Widget build(BuildContext context) {
    final canPop = Navigator.of(context).canPop();
    final isWide = MediaQuery.of(context).size.width >= 720;

    return Container(
      color: colors.topBarBg,
      padding: const EdgeInsets.fromLTRB(16, 18, 16, 16),
      child: isWide
          ? Row(
              children: [
                if (canPop) ...[
                  _TopNavButton(
                    icon: Icons.arrow_back_ios_new_rounded,
                    onTap: () => Navigator.of(context).pop(),
                  ),
                  const SizedBox(width: 10),
                ],
                _TopPageIcon(colors: colors),
                const SizedBox(width: 12),
                const Expanded(child: _TopBarText()),
                _TopStatPill(label: 'รายการ', value: '$totalItems'),
                const SizedBox(width: 8),
                _TopStatPill(label: 'สลิป', value: '$totalSlips'),
                const SizedBox(width: 8),
                FilledButton.icon(
                  onPressed: onPrint,
                  icon: isPrinting
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Icon(Icons.print_outlined, size: 18),
                  label: const Text('พิมพ์'),
                  style: FilledButton.styleFrom(
                    backgroundColor: AppTheme.primary,
                    foregroundColor: Colors.white,
                  ),
                ),
              ],
            )
          : Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    if (canPop) ...[
                      _TopNavButton(
                        icon: Icons.arrow_back_ios_new_rounded,
                        onTap: () => Navigator.of(context).pop(),
                      ),
                      const SizedBox(width: 10),
                    ],
                    _TopPageIcon(colors: colors),
                    const SizedBox(width: 12),
                    const Expanded(child: _TopBarText()),
                  ],
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    _TopStatPill(label: 'รายการ', value: '$totalItems'),
                    const SizedBox(width: 8),
                    _TopStatPill(label: 'สลิป', value: '$totalSlips'),
                    const Spacer(),
                    FilledButton.icon(
                      onPressed: onPrint,
                      icon: isPrinting
                          ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: Colors.white,
                              ),
                            )
                          : const Icon(Icons.print_outlined, size: 18),
                      label: const Text('พิมพ์'),
                    ),
                  ],
                ),
              ],
            ),
    );
  }
}

class _TopBarText extends StatelessWidget {
  const _TopBarText();

  @override
  Widget build(BuildContext context) {
    return const Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'สร้างบาร์โค้ดสินค้า',
          style: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: Colors.white,
          ),
        ),
        SizedBox(height: 2),
        Text(
          'เพิ่มรายการ, สร้างค่าบาร์โค้ดอัตโนมัติ และเรียกใช้จาก history ได้ทันที',
          style: TextStyle(fontSize: 12, color: Colors.white70),
        ),
      ],
    );
  }
}

class _TopNavButton extends StatelessWidget {
  final IconData icon;
  final VoidCallback onTap;

  const _TopNavButton({required this.icon, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(10),
      child: Container(
        width: 40,
        height: 40,
        decoration: BoxDecoration(
          color: Colors.white.withValues(alpha: 0.08),
          borderRadius: BorderRadius.circular(10),
          border: Border.all(color: Colors.white24),
        ),
        child: Icon(icon, size: 18, color: Colors.white),
      ),
    );
  }
}

class _TopPageIcon extends StatelessWidget {
  final _BarcodePageColors colors;

  const _TopPageIcon({required this.colors});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 42,
      height: 42,
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white24),
      ),
      child: const Icon(Icons.qr_code_2_rounded, color: Colors.white),
    );
  }
}

class _TopStatPill extends StatelessWidget {
  final String label;
  final String value;

  const _TopStatPill({required this.label, required this.value});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(999),
        border: Border.all(color: Colors.white24),
      ),
      child: RichText(
        text: TextSpan(
          children: [
            TextSpan(
              text: '$label ',
              style: const TextStyle(fontSize: 12, color: Colors.white70),
            ),
            TextSpan(
              text: value,
              style: const TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.w700,
                color: Colors.white,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _BarcodeSummaryBar extends StatelessWidget {
  final _BarcodePageColors colors;
  final int totalItems;
  final int totalSlips;
  final int historyCount;
  final String typeLabel;

  const _BarcodeSummaryBar({
    required this.colors,
    required this.totalItems,
    required this.totalSlips,
    required this.historyCount,
    required this.typeLabel,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
        color: colors.summaryBg,
        border: Border(bottom: BorderSide(color: colors.border)),
      ),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
      child: Wrap(
        spacing: 8,
        runSpacing: 8,
        children: [
          _SummaryChip(
            label: 'รายการทั้งหมด',
            value: '$totalItems',
            color: AppTheme.info,
          ),
          _SummaryChip(
            label: 'สลิปพิมพ์',
            value: '$totalSlips',
            color: AppTheme.primary,
          ),
          _SummaryChip(
            label: 'History',
            value: '$historyCount',
            color: AppTheme.success,
          ),
          _SummaryChip(
            label: 'ประเภท',
            value: typeLabel,
            color: AppTheme.warning,
          ),
        ],
      ),
    );
  }
}

class _SummaryChip extends StatelessWidget {
  final String label;
  final String value;
  final Color color;

  const _SummaryChip({
    required this.label,
    required this.value,
    required this.color,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 7),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(999),
        border: Border.all(color: color.withValues(alpha: 0.2)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            '$label ',
            style: TextStyle(
              fontSize: 12,
              color: color,
              fontWeight: FontWeight.w500,
            ),
          ),
          Text(
            value,
            style: TextStyle(
              fontSize: 12,
              color: color,
              fontWeight: FontWeight.w700,
            ),
          ),
        ],
      ),
    );
  }
}

class _BarcodeMainPanel extends StatelessWidget {
  final _BarcodePageColors colors;
  final BarcodePdfType type;
  final int columnsPerRow;
  final ValueChanged<BarcodePdfType> onTypeChanged;
  final ValueChanged<int> onColumnsChanged;
  final Widget child;

  const _BarcodeMainPanel({
    required this.colors,
    required this.type,
    required this.columnsPerRow,
    required this.onTypeChanged,
    required this.onColumnsChanged,
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: colors.cardBg,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: colors.border),
        boxShadow: [
          if (!colors.isDark)
            BoxShadow(
              color: AppTheme.navy.withValues(alpha: 0.04),
              blurRadius: 16,
              offset: const Offset(0, 6),
            ),
        ],
      ),
      child: Column(
        children: [
          _PrintSettingsBar(
            colors: colors,
            type: type,
            columnsPerRow: columnsPerRow,
            onTypeChanged: onTypeChanged,
            onColumnsChanged: onColumnsChanged,
          ),
          Expanded(child: child),
        ],
      ),
    );
  }
}

class _PrintSettingsBar extends StatelessWidget {
  final _BarcodePageColors colors;
  final BarcodePdfType type;
  final int columnsPerRow;
  final ValueChanged<BarcodePdfType> onTypeChanged;
  final ValueChanged<int> onColumnsChanged;

  const _PrintSettingsBar({
    required this.colors,
    required this.type,
    required this.columnsPerRow,
    required this.onTypeChanged,
    required this.onColumnsChanged,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: colors.summaryBg,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(14)),
        border: Border(bottom: BorderSide(color: colors.border)),
      ),
      child: Wrap(
        spacing: 16,
        runSpacing: 12,
        crossAxisAlignment: WrapCrossAlignment.center,
        children: [
          _SettingGroup(
            label: 'ประเภทบาร์โค้ด',
            child: SegmentedButton<BarcodePdfType>(
              showSelectedIcon: false,
              segments: const [
                ButtonSegment(
                  value: BarcodePdfType.code128,
                  label: Text('Code128'),
                ),
                ButtonSegment(
                  value: BarcodePdfType.ean13,
                  label: Text('EAN-13'),
                ),
                ButtonSegment(value: BarcodePdfType.qrCode, label: Text('QR')),
              ],
              selected: {type},
              onSelectionChanged: (s) => onTypeChanged(s.first),
            ),
          ),
          _SettingGroup(
            label: 'คอลัมน์ต่อแถว',
            child: SegmentedButton<int>(
              showSelectedIcon: false,
              segments: const [
                ButtonSegment(value: 2, label: Text('2')),
                ButtonSegment(value: 3, label: Text('3')),
                ButtonSegment(value: 4, label: Text('4')),
              ],
              selected: {columnsPerRow},
              onSelectionChanged: (s) => onColumnsChanged(s.first),
            ),
          ),
        ],
      ),
    );
  }
}

class _SettingGroup extends StatelessWidget {
  final String label;
  final Widget child;

  const _SettingGroup({required this.label, required this.child});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          label,
          style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w600),
        ),
        const SizedBox(height: 8),
        child,
      ],
    );
  }
}

class _ItemRow extends StatefulWidget {
  final _BarcodeItem item;
  final _BarcodePageColors colors;
  final bool isSelected;
  final VoidCallback onActivate;
  final VoidCallback onRemove;
  final VoidCallback onGenerateBarcode;
  final ValueChanged<String> onNameChanged;
  final ValueChanged<String> onBarcodeChanged;
  final ValueChanged<int> onQtyChanged;

  const _ItemRow({
    required this.item,
    required this.colors,
    required this.isSelected,
    required this.onActivate,
    required this.onRemove,
    required this.onGenerateBarcode,
    required this.onNameChanged,
    required this.onBarcodeChanged,
    required this.onQtyChanged,
  });

  @override
  State<_ItemRow> createState() => _ItemRowState();
}

class _ItemRowState extends State<_ItemRow> {
  late final TextEditingController _nameCtrl;
  late final TextEditingController _barcodeCtrl;
  late final TextEditingController _qtyCtrl;

  @override
  void initState() {
    super.initState();
    _nameCtrl = TextEditingController(text: widget.item.name);
    _barcodeCtrl = TextEditingController(text: widget.item.barcodeValue);
    _qtyCtrl = TextEditingController(text: widget.item.qty.toString());
  }

  @override
  void didUpdateWidget(covariant _ItemRow oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.item.name != widget.item.name &&
        _nameCtrl.text != widget.item.name) {
      _nameCtrl.text = widget.item.name;
    }
    if (oldWidget.item.barcodeValue != widget.item.barcodeValue &&
        _barcodeCtrl.text != widget.item.barcodeValue) {
      _barcodeCtrl.text = widget.item.barcodeValue;
    }
    final qtyText = widget.item.qty.toString();
    if (oldWidget.item.qty != widget.item.qty && _qtyCtrl.text != qtyText) {
      _qtyCtrl.text = qtyText;
    }
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    _barcodeCtrl.dispose();
    _qtyCtrl.dispose();
    super.dispose();
  }

  void _stepQty(int delta) {
    final v = int.tryParse(_qtyCtrl.text) ?? 1;
    final next = (v + delta).clamp(1, 999);
    _qtyCtrl.text = next.toString();
    widget.onQtyChanged(next);
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 0,
      margin: EdgeInsets.zero,
      color: widget.colors.cardBg,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(
          color: widget.isSelected ? AppTheme.primary : widget.colors.border,
          width: widget.isSelected ? 1.4 : 1,
        ),
      ),
      child: InkWell(
        onTap: widget.onActivate,
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
          child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: ConstrainedBox(
              constraints: const BoxConstraints(minWidth: 760),
              child: Row(
                children: [
                  Container(
                    width: 30,
                    height: 30,
                    decoration: BoxDecoration(
                      color: widget.isSelected
                          ? AppTheme.primary.withValues(alpha: 0.16)
                          : AppTheme.primary.withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Icon(
                      widget.isSelected
                          ? Icons.radio_button_checked
                          : Icons.inventory_2_outlined,
                      size: 16,
                      color: AppTheme.primary,
                    ),
                  ),
                  const SizedBox(width: 8),
                  SizedBox(width: 220, child: _buildNameField()),
                  const SizedBox(width: 8),
                  SizedBox(width: 260, child: _buildBarcodeField()),
                  const SizedBox(width: 8),
                  SizedBox(width: 120, child: _buildQtyField()),
                  const SizedBox(width: 8),
                  if (widget.item.autoGenerated)
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 3,
                      ),
                      decoration: BoxDecoration(
                        color: AppTheme.info.withValues(alpha: 0.1),
                        borderRadius: BorderRadius.circular(999),
                      ),
                      child: const Text(
                        'AUTO',
                        style: TextStyle(
                          fontSize: 9,
                          fontWeight: FontWeight.w700,
                          color: AppTheme.info,
                        ),
                      ),
                    )
                  else
                    Text(
                      '${widget.item.qty} สลิป',
                      style: TextStyle(
                        fontSize: 10,
                        color: widget.colors.subtext,
                      ),
                    ),
                  const SizedBox(width: 4),
                  IconButton(
                    visualDensity: VisualDensity.compact,
                    icon: const Icon(
                      Icons.delete_outline,
                      color: AppTheme.error,
                      size: 18,
                    ),
                    tooltip: 'ลบรายการนี้',
                    onPressed: widget.onRemove,
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildNameField() {
    return TextField(
      controller: _nameCtrl,
      onTap: widget.onActivate,
      decoration: const InputDecoration(
        labelText: 'ชื่อสินค้า',
        isDense: true,
        border: OutlineInputBorder(),
        contentPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 9),
        labelStyle: TextStyle(fontSize: 11),
      ),
      style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w500),
      onChanged: widget.onNameChanged,
    );
  }

  Widget _buildBarcodeField() {
    return TextField(
      controller: _barcodeCtrl,
      onTap: widget.onActivate,
      decoration: InputDecoration(
        labelText: 'ค่าบาร์โค้ด',
        isDense: true,
        border: const OutlineInputBorder(),
        contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 9),
        labelStyle: const TextStyle(fontSize: 11),
        suffixIcon: IconButton(
          tooltip: 'สร้างอัตโนมัติ',
          onPressed: widget.onGenerateBarcode,
          icon: const Icon(Icons.auto_awesome_outlined, size: 16),
        ),
      ),
      style: TextStyle(fontSize: 13, color: widget.colors.subtext),
      onChanged: widget.onBarcodeChanged,
    );
  }

  Widget _buildQtyField() {
    return Row(
      children: [
        _StepBtn(icon: Icons.remove, onTap: () => _stepQty(-1)),
        Expanded(
          child: TextField(
            controller: _qtyCtrl,
            onTap: widget.onActivate,
            textAlign: TextAlign.center,
            keyboardType: TextInputType.number,
            inputFormatters: [FilteringTextInputFormatter.digitsOnly],
            decoration: const InputDecoration(
              isDense: true,
              border: OutlineInputBorder(),
              hintText: 'Qty',
              hintStyle: TextStyle(fontSize: 11),
              contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 9),
            ),
            style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600),
            onChanged: (v) {
              final n = int.tryParse(v);
              if (n != null && n > 0) widget.onQtyChanged(n);
            },
          ),
        ),
        _StepBtn(icon: Icons.add, onTap: () => _stepQty(1)),
      ],
    );
  }
}

class _StepBtn extends StatelessWidget {
  final IconData icon;
  final VoidCallback onTap;

  const _StepBtn({required this.icon, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(8),
      child: Padding(
        padding: const EdgeInsets.all(8),
        child: Icon(icon, size: 18),
      ),
    );
  }
}

class _EmptyState extends StatelessWidget {
  final _BarcodePageColors colors;
  final VoidCallback onAdd;

  const _EmptyState({required this.colors, required this.onAdd});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 82,
              height: 82,
              decoration: BoxDecoration(
                color: colors.summaryBg,
                shape: BoxShape.circle,
              ),
              child: Icon(
                Icons.qr_code_2_outlined,
                size: 42,
                color: colors.emptyIcon,
              ),
            ),
            const SizedBox(height: 14),
            Text(
              'ยังไม่มีสินค้าในรายการ',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w700,
                color: colors.text,
              ),
            ),
            const SizedBox(height: 6),
            Text(
              'กดเพิ่มช่องเพื่อสร้างบาร์โค้ดอัตโนมัติ หรือเลือกจากสินค้า/History ได้เลย',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 12, color: colors.subtext),
            ),
            const SizedBox(height: 18),
            FilledButton.icon(
              onPressed: onAdd,
              icon: const Icon(Icons.add),
              label: const Text('เพิ่มรายการแรก'),
            ),
          ],
        ),
      ),
    );
  }
}

class _BarcodeHistoryPanel extends StatefulWidget {
  final _BarcodePageColors colors;
  final List<_BarcodeHistoryEntry> entries;
  final String query;
  final bool isLoading;
  final ValueChanged<String> onQueryChanged;
  final ValueChanged<_BarcodeHistoryEntry> onUse;
  final ValueChanged<String> onRemove;
  final Future<void> Function() onClear;

  const _BarcodeHistoryPanel({
    required this.colors,
    required this.entries,
    required this.query,
    required this.isLoading,
    required this.onQueryChanged,
    required this.onUse,
    required this.onRemove,
    required this.onClear,
  });

  @override
  State<_BarcodeHistoryPanel> createState() => _BarcodeHistoryPanelState();
}

class _BarcodeHistoryPanelState extends State<_BarcodeHistoryPanel> {
  late final TextEditingController _searchCtrl;

  @override
  void initState() {
    super.initState();
    _searchCtrl = TextEditingController(text: widget.query);
  }

  @override
  void didUpdateWidget(covariant _BarcodeHistoryPanel oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.query != _searchCtrl.text) {
      _searchCtrl.value = TextEditingValue(
        text: widget.query,
        selection: TextSelection.collapsed(offset: widget.query.length),
      );
    }
  }

  @override
  void dispose() {
    _searchCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: widget.colors.cardBg,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: widget.colors.border),
        boxShadow: [
          if (!widget.colors.isDark)
            BoxShadow(
              color: AppTheme.navy.withValues(alpha: 0.04),
              blurRadius: 16,
              offset: const Offset(0, 6),
            ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 12),
            child: Row(
              children: [
                Expanded(
                  child: Text(
                    'Barcode History',
                    style: TextStyle(
                      fontSize: 15,
                      fontWeight: FontWeight.w700,
                      color: widget.colors.text,
                    ),
                  ),
                ),
                if (widget.entries.isNotEmpty)
                  TextButton(
                    onPressed: widget.onClear,
                    child: const Text('ล้างทั้งหมด'),
                  ),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
            child: TextField(
              controller: _searchCtrl,
              onChanged: widget.onQueryChanged,
              decoration: const InputDecoration(
                hintText: 'ค้นหา barcode หรือชื่อสินค้า',
                prefixIcon: Icon(Icons.search),
                isDense: true,
                border: OutlineInputBorder(),
              ),
            ),
          ),
          Divider(height: 1, color: widget.colors.border),
          Expanded(
            child: widget.isLoading
                ? const Center(child: CircularProgressIndicator())
                : widget.entries.isEmpty
                ? Center(
                    child: Padding(
                      padding: const EdgeInsets.all(20),
                      child: Text(
                        'บาร์โค้ดที่กรอกหรือสร้างไว้จะถูกบันทึกไว้ตรงนี้',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          fontSize: 12,
                          color: widget.colors.subtext,
                        ),
                      ),
                    ),
                  )
                : ListView.separated(
                    padding: const EdgeInsets.all(12),
                    itemCount: widget.entries.length,
                    separatorBuilder: (_, _) => const SizedBox(height: 8),
                    itemBuilder: (_, i) {
                      final entry = widget.entries[i];
                      return InkWell(
                        onTap: () => widget.onUse(entry),
                        borderRadius: BorderRadius.circular(12),
                        child: Container(
                          padding: const EdgeInsets.all(12),
                          decoration: BoxDecoration(
                            color: widget.colors.summaryBg,
                            borderRadius: BorderRadius.circular(12),
                            border: Border.all(color: widget.colors.border),
                          ),
                          child: Row(
                            children: [
                              Container(
                                width: 34,
                                height: 34,
                                decoration: BoxDecoration(
                                  color: AppTheme.info.withValues(alpha: 0.1),
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                child: const Icon(
                                  Icons.history,
                                  size: 18,
                                  color: AppTheme.info,
                                ),
                              ),
                              const SizedBox(width: 10),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      entry.name.isEmpty
                                          ? 'ไม่มีชื่อสินค้า'
                                          : entry.name,
                                      style: TextStyle(
                                        fontSize: 13,
                                        fontWeight: FontWeight.w600,
                                        color: widget.colors.text,
                                      ),
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                    const SizedBox(height: 2),
                                    Text(
                                      entry.barcodeValue,
                                      style: TextStyle(
                                        fontSize: 12,
                                        color: widget.colors.subtext,
                                      ),
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                  ],
                                ),
                              ),
                              IconButton(
                                tooltip: 'ลบจาก history',
                                onPressed: () =>
                                    widget.onRemove(entry.barcodeValue),
                                icon: const Icon(
                                  Icons.close,
                                  size: 18,
                                  color: AppTheme.error,
                                ),
                              ),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}

class _BottomBar extends StatelessWidget {
  final _BarcodePageColors colors;
  final List<ProductModel> products;
  final bool isPreviewing;
  final bool isSharing;
  final bool hasItems;
  final VoidCallback onAddManual;
  final ValueChanged<ProductModel> onAddFromProduct;
  final VoidCallback onPreview;
  final VoidCallback onShare;

  const _BottomBar({
    required this.colors,
    required this.products,
    required this.isPreviewing,
    required this.isSharing,
    required this.hasItems,
    required this.onAddManual,
    required this.onAddFromProduct,
    required this.onPreview,
    required this.onShare,
  });

  @override
  Widget build(BuildContext context) {
    final busy = isPreviewing || isSharing;
    final isCompact = MediaQuery.of(context).size.width < 760;

    return SafeArea(
      top: false,
      child: Container(
        padding: const EdgeInsets.fromLTRB(12, 10, 12, 12),
        decoration: BoxDecoration(
          color: colors.cardBg,
          border: Border(top: BorderSide(color: colors.border)),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withValues(alpha: 0.06),
              blurRadius: 10,
              offset: const Offset(0, -2),
            ),
          ],
        ),
        child: isCompact
            ? Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: _AddFromProductBtn(
                          products: products,
                          onSelected: onAddFromProduct,
                        ),
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: OutlinedButton.icon(
                          onPressed: onAddManual,
                          icon: const Icon(Icons.add, size: 16),
                          label: const Text('เพิ่มช่อง'),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      Expanded(
                        child: OutlinedButton.icon(
                          onPressed: (hasItems && !busy) ? onPreview : null,
                          icon: isPreviewing
                              ? const SizedBox(
                                  width: 16,
                                  height: 16,
                                  child: CircularProgressIndicator(
                                    strokeWidth: 2,
                                  ),
                                )
                              : const Icon(
                                  Icons.picture_as_pdf_outlined,
                                  size: 18,
                                ),
                          label: const Text('PDF'),
                        ),
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: FilledButton.icon(
                          onPressed: (hasItems && !busy) ? onShare : null,
                          icon: isSharing
                              ? const SizedBox(
                                  width: 16,
                                  height: 16,
                                  child: CircularProgressIndicator(
                                    strokeWidth: 2,
                                    color: Colors.white,
                                  ),
                                )
                              : const Icon(Icons.share_outlined, size: 18),
                          label: const Text('แชร์'),
                        ),
                      ),
                    ],
                  ),
                ],
              )
            : Row(
                children: [
                  _AddFromProductBtn(
                    products: products,
                    onSelected: onAddFromProduct,
                  ),
                  const SizedBox(width: 8),
                  OutlinedButton.icon(
                    onPressed: onAddManual,
                    icon: const Icon(Icons.add, size: 16),
                    label: const Text('เพิ่มช่อง'),
                  ),
                  const Spacer(),
                  OutlinedButton.icon(
                    onPressed: (hasItems && !busy) ? onPreview : null,
                    icon: isPreviewing
                        ? const SizedBox(
                            width: 16,
                            height: 16,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : const Icon(Icons.picture_as_pdf_outlined, size: 18),
                    label: const Text('PDF'),
                  ),
                  const SizedBox(width: 8),
                  FilledButton.icon(
                    onPressed: (hasItems && !busy) ? onShare : null,
                    icon: isSharing
                        ? const SizedBox(
                            width: 16,
                            height: 16,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              color: Colors.white,
                            ),
                          )
                        : const Icon(Icons.share_outlined, size: 18),
                    label: const Text('แชร์'),
                    style: FilledButton.styleFrom(
                      backgroundColor: AppTheme.primary,
                    ),
                  ),
                ],
              ),
      ),
    );
  }
}

class _AddFromProductBtn extends StatefulWidget {
  final List<ProductModel> products;
  final ValueChanged<ProductModel> onSelected;

  const _AddFromProductBtn({required this.products, required this.onSelected});

  @override
  State<_AddFromProductBtn> createState() => _AddFromProductBtnState();
}

class _AddFromProductBtnState extends State<_AddFromProductBtn> {
  final _searchCtrl = TextEditingController();
  String _query = '';

  @override
  void dispose() {
    _searchCtrl.dispose();
    super.dispose();
  }

  void _show() {
    _searchCtrl.clear();
    setState(() => _query = '');
    showModalBottomSheet<ProductModel>(
      context: context,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
      ),
      builder: (ctx) => StatefulBuilder(
        builder: (ctx, setModal) => DraggableScrollableSheet(
          expand: false,
          initialChildSize: 0.65,
          maxChildSize: 0.92,
          builder: (_, sc) => Column(
            children: [
              Container(
                width: 42,
                height: 4,
                margin: const EdgeInsets.symmetric(vertical: 10),
                decoration: BoxDecoration(
                  color: Colors.grey.shade400,
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
              Padding(
                padding: const EdgeInsets.fromLTRB(16, 0, 16, 8),
                child: TextField(
                  controller: _searchCtrl,
                  autofocus: true,
                  decoration: const InputDecoration(
                    hintText: 'ค้นหาสินค้า...',
                    prefixIcon: Icon(Icons.search),
                    border: OutlineInputBorder(),
                    isDense: true,
                  ),
                  onChanged: (v) => setModal(() => _query = v.toLowerCase()),
                ),
              ),
              Expanded(
                child: ListView.separated(
                  controller: sc,
                  itemCount: _filtered.length,
                  separatorBuilder: (_, _) => const Divider(height: 1),
                  itemBuilder: (_, i) {
                    final p = _filtered[i];
                    return ListTile(
                      dense: true,
                      leading: const Icon(Icons.inventory_2_outlined, size: 20),
                      title: Text(
                        p.productName,
                        style: const TextStyle(fontSize: 13),
                      ),
                      subtitle: Text(
                        '${p.productCode}${p.barcode != null ? " • ${p.barcode}" : ""}',
                        style: const TextStyle(fontSize: 11),
                      ),
                      onTap: () {
                        Navigator.pop(ctx);
                        widget.onSelected(p);
                      },
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  List<ProductModel> get _filtered {
    if (_query.isEmpty) return widget.products;
    return widget.products.where((p) {
      return p.productName.toLowerCase().contains(_query) ||
          p.productCode.toLowerCase().contains(_query) ||
          (p.barcode?.toLowerCase().contains(_query) ?? false);
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    return FilledButton.tonalIcon(
      onPressed: _show,
      icon: const Icon(Icons.inventory_2_outlined, size: 16),
      label: const Text('เลือกจากสินค้า'),
    );
  }
}

class _BarcodePageColors {
  final bool isDark;
  final Color scaffoldBg;
  final Color cardBg;
  final Color border;
  final Color text;
  final Color subtext;
  final Color topBarBg;
  final Color summaryBg;
  final Color emptyIcon;

  const _BarcodePageColors({
    required this.isDark,
    required this.scaffoldBg,
    required this.cardBg,
    required this.border,
    required this.text,
    required this.subtext,
    required this.topBarBg,
    required this.summaryBg,
    required this.emptyIcon,
  });

  factory _BarcodePageColors.of(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return _BarcodePageColors(
      isDark: isDark,
      scaffoldBg: isDark ? AppTheme.darkBg : AppTheme.surface,
      cardBg: isDark ? const Color(0xFF2C2C2C) : Colors.white,
      border: isDark ? const Color(0xFF333333) : AppTheme.border,
      text: isDark ? const Color(0xFFE0E0E0) : const Color(0xFF1A1A1A),
      subtext: isDark ? const Color(0xFF9E9E9E) : AppTheme.textSub,
      topBarBg: isDark ? AppTheme.navyDark : AppTheme.navy,
      summaryBg: isDark ? const Color(0xFF181818) : const Color(0xFFFFF8F5),
      emptyIcon: isDark ? const Color(0xFF9E9E9E) : Colors.grey,
    );
  }
}

extension on BarcodePdfType {
  String get label {
    switch (this) {
      case BarcodePdfType.code128:
        return 'Code128';
      case BarcodePdfType.ean13:
        return 'EAN-13';
      case BarcodePdfType.qrCode:
        return 'QR';
    }
  }
}
