import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:file_picker/file_picker.dart';
import '../providers/product_provider.dart';
import '../../data/models/product_model.dart';
import '../../../../shared/services/mobile_scanner_service.dart';
import 'package:pos_erp/shared/theme/app_theme.dart';


// ─────────────────────────────────────────────────────────────────
// ProductFormPage
// ─────────────────────────────────────────────────────────────────
class ProductFormPage extends ConsumerStatefulWidget {
  final ProductModel? product;
  const ProductFormPage({super.key, this.product});

  @override
  ConsumerState<ProductFormPage> createState() => _ProductFormPageState();
}

class _ProductFormPageState extends ConsumerState<ProductFormPage> {
  final _formKey = GlobalKey<FormState>();

  late final TextEditingController _codeController;
  late final TextEditingController _nameController;
  late final TextEditingController _barcodeController;
  late final TextEditingController _unitController;
  late final TextEditingController _price1Controller;
  late final TextEditingController _price2Controller;
  late final TextEditingController _price3Controller;
  late final TextEditingController _price4Controller;
  late final TextEditingController _price5Controller;
  late final TextEditingController _costController;

  bool _isStockControl    = true;
  bool _allowNegativeStock = false;
  bool _isLoading          = false;
  bool _codeAutoGenerated  = false; // ✅ ติดตามว่ารหัสถูก generate อัตโนมัติ

  String? _imagePath;

  @override
  void initState() {
    super.initState();
    final p = widget.product;
    _codeController    = TextEditingController(text: p?.productCode ?? '');
    _nameController    = TextEditingController(text: p?.productName ?? '');
    _barcodeController = TextEditingController(text: p?.barcode ?? '');
    _unitController    = TextEditingController(text: p?.baseUnit ?? 'ชิ้น');
    _price1Controller  = TextEditingController(text: p?.priceLevel1.toString() ?? '0');
    _price2Controller  = TextEditingController(text: p?.priceLevel2.toString() ?? '0');
    _price3Controller  = TextEditingController(text: p?.priceLevel3.toString() ?? '0');
    _price4Controller  = TextEditingController(text: p?.priceLevel4.toString() ?? '0');
    _price5Controller  = TextEditingController(text: p?.priceLevel5.toString() ?? '0');
    _costController    = TextEditingController(text: p?.standardCost.toString() ?? '0');

    if (p != null) {
      _isStockControl     = p.isStockControl;
      _allowNegativeStock = p.allowNegativeStock;
      _imagePath          = p.imagePath;
    }

    // ✅ เมื่อ barcode เปลี่ยน → อัปเดตรหัสสินค้า (เฉพาะ create mode)
    if (widget.product == null) {
      _barcodeController.addListener(_onBarcodeChanged);
    }
  }

  // ─────────────────────────────────────────────────────────────
  // Auto-generate product code
  // ─────────────────────────────────────────────────────────────

  /// เรียกเมื่อ barcode field เปลี่ยน (create mode เท่านั้น)
  void _onBarcodeChanged() {
    final barcode = _barcodeController.text.trim();
    // ถ้า user ยังไม่ได้แก้รหัสเอง หรือรหัสเป็น auto-generated ก่อนหน้า
    if (_codeAutoGenerated || _codeController.text.isEmpty) {
      if (barcode.isNotEmpty) {
        // ใช้ barcode เป็นรหัสสินค้า
        _codeController.text = barcode;
      } else {
        // barcode ว่าง → generate รหัสจาก timestamp
        _codeController.text = _generateCode();
      }
      _codeAutoGenerated = true;
    }
  }

  /// สร้างรหัสสินค้าอัตโนมัติ เช่น PRD-250321-001
  String _generateCode() {
    final now = DateTime.now();
    final date =
        '${now.year.toString().substring(2)}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}';
    final seq = (now.millisecondsSinceEpoch % 1000).toString().padLeft(3, '0');
    return 'PRD-$date-$seq';
  }

  /// กด "สร้างรหัสอัตโนมัติ" ด้วยตนเอง
  void _autoGenerateCode() {
    final barcode = _barcodeController.text.trim();
    setState(() {
      _codeController.text =
          barcode.isNotEmpty ? barcode : _generateCode();
      _codeAutoGenerated = true;
    });
  }

  @override
  void dispose() {
    _barcodeController.removeListener(_onBarcodeChanged);
    _codeController.dispose();
    _nameController.dispose();
    _barcodeController.dispose();
    _unitController.dispose();
    _price1Controller.dispose();
    _price2Controller.dispose();
    _price3Controller.dispose();
    _price4Controller.dispose();
    _price5Controller.dispose();
    _costController.dispose();
    super.dispose();
  }

  // ─────────────────────────────────────────────────────────────
  // Image picker
  // ─────────────────────────────────────────────────────────────
  Future<void> _pickImage() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.image,
      allowMultiple: false,
    );
    if (result == null || result.files.isEmpty) return;
    final path = result.files.first.path;
    if (path == null) return;
    setState(() => _imagePath = path);
  }

  void _removeImage() => setState(() => _imagePath = null);

  // ─────────────────────────────────────────────────────────────
  // Submit
  // ─────────────────────────────────────────────────────────────
  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isLoading = true);

    double d(TextEditingController c) =>
        double.tryParse(c.text.isEmpty ? '0' : c.text) ?? 0;

    final data = {
      'product_code': _codeController.text.trim(),
      'product_name': _nameController.text.trim(),
      'barcode': _barcodeController.text.trim().isEmpty
          ? null
          : _barcodeController.text.trim(),
      'base_unit': _unitController.text.trim(),
      'price_level1': d(_price1Controller),
      'price_level2': d(_price2Controller),
      'price_level3': d(_price3Controller),
      'price_level4': d(_price4Controller),
      'price_level5': d(_price5Controller),
      'standard_cost': d(_costController),
      'is_stock_control': _isStockControl,
      'allow_negative_stock': _allowNegativeStock,
      'image_path': _imagePath,
    };

    final bool success;
    if (widget.product != null) {
      success = await ref
          .read(productListProvider.notifier)
          .updateProduct(widget.product!.productId, data);
    } else {
      success =
          await ref.read(productListProvider.notifier).addProduct(data);
    }

    if (mounted) {
      setState(() => _isLoading = false);
      if (success) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(widget.product != null
              ? 'แก้ไขสินค้าสำเร็จ'
              : 'เพิ่มสินค้าสำเร็จ'),
          backgroundColor: AppTheme.successColor,
        ));
      } else {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
          content: Text('เกิดข้อผิดพลาด กรุณาลองใหม่'),
          backgroundColor: AppTheme.errorColor,
        ));
      }
    }
  }

  // ─────────────────────────────────────────────────────────────
  // Build
  // ─────────────────────────────────────────────────────────────
  @override
  Widget build(BuildContext context) {
    final isEdit = widget.product != null;

    return Scaffold(
      backgroundColor: Theme.of(context).brightness == Brightness.dark
          ? AppTheme.darkBg
          : const Color(0xFFF5F5F5),
      body: Column(
        children: [
          // ── Title Bar ─────────────────────────────────────────
          _TitleBar(isEdit: isEdit),

          // ── Form Body ─────────────────────────────────────────
          Expanded(
            child: Form(
              key: _formKey,
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(20),
                child: Column(
                  children: [
                    // ══ Row 1 (Responsive) ════════════════════
                    LayoutBuilder(builder: (ctx, bc) {
                      final isWide = bc.maxWidth >= 880;
                      final c1 = _SectionCard(
                              icon: Icons.inventory_2_outlined,
                              iconColor: AppTheme.primary,
                              title: 'ข้อมูลสินค้า',
                              child: Column(
                                children: [
                                  // ① บาร์โค้ด (ขึ้นก่อน)
                                  _BarcodeField(
                                    controller: _barcodeController,
                                    enabled: !_isLoading,
                                    onScanned: (val) {
                                      setState(() {
                                        _barcodeController.text = val;
                                        // trigger listener
                                        _onBarcodeChanged();
                                      });
                                    },
                                  ),
                                  const SizedBox(height: 14),

                                  // ② รหัสสินค้า (auto จาก barcode)
                                  _ProductCodeField(
                                    controller: _codeController,
                                    isEdit: isEdit,
                                    isAutoGenerated: _codeAutoGenerated,
                                    enabled: !_isLoading,
                                    onAutoGenerate: _autoGenerateCode,
                                    onManualEdit: () =>
                                        setState(() => _codeAutoGenerated = false),
                                  ),
                                  const SizedBox(height: 14),

                                  // ③ ชื่อสินค้า
                                  _FormField(
                                    controller: _nameController,
                                    label: 'ชื่อสินค้า',
                                    icon: Icons.label_outlined,
                                    required: true,
                                    enabled: !_isLoading,
                                    validator: (v) => (v == null || v.isEmpty)
                                        ? 'กรุณากรอกชื่อสินค้า'
                                        : null,
                                  ),
                                  const SizedBox(height: 14),

                                  // ④ หน่วย
                                  _FormField(
                                    controller: _unitController,
                                    label: 'หน่วย',
                                    icon: Icons.straighten_outlined,
                                    required: true,
                                    enabled: !_isLoading,
                                    validator: (v) => (v == null || v.isEmpty)
                                        ? 'กรุณากรอกหน่วย'
                                        : null,
                                  ),
                                ],
                              ),
                            );
                      final c2 = _SectionCard(
                              icon: Icons.sell_outlined,
                              iconColor: AppTheme.info,
                              title: 'ราคาขาย',
                              child: Column(
                                children: [
                                  // ── Level 1 — ราคาปกติ (required) ────
                                  _FormField(
                                    controller: _price1Controller,
                                    label: 'Level 1 — ราคาปกติ / ลูกค้าทั่วไป',
                                    icon: Icons.monetization_on_outlined,
                                    required: true,
                                    keyboardType: TextInputType.number,
                                    enabled: !_isLoading,
                                    prefixText: '฿',                                    
                                    validator: (v) => (v == null || v.isEmpty)
                                        ? 'กรุณากรอกราคา'
                                        : null,
                                  ),
                                  const SizedBox(height: 14),
                                  // ── Level 2 & 3 ───────────────────────
                                  _PriceRow(
                                    c1: _price2Controller,
                                    l1: 'Level 2',
                                    h1: 'ราคาสมาชิก',
                                    c2: _price3Controller,
                                    l2: 'Level 3',
                                    h2: 'ราคาส่ง',
                                    enabled: !_isLoading,
                                  ),
                                  const SizedBox(height: 10),
                                  // ── Level 4 & 5 ───────────────────────
                                  _PriceRow(
                                    c1: _price4Controller,
                                    l1: 'Level 4',
                                    h1: 'ราคาตัวแทน',
                                    c2: _price5Controller,
                                    l2: 'Level 5',
                                    h2: 'ราคา VIP / พิเศษ',
                                    enabled: !_isLoading,
                                  ),
                                  const SizedBox(height: 14),
                                  // ── ต้นทุน ────────────────────────────
                                  _FormField(
                                    controller: _costController,
                                    label: 'ต้นทุนมาตรฐาน',
                                    icon: Icons.price_change_outlined,
                                    keyboardType: TextInputType.number,
                                    enabled: !_isLoading,
                                    prefixText: '฿',
                                    helperText: 'ใช้คำนวณกำไรขั้นต้น',
                                  ),
                                ],
                              ),
                            );
                      final c3 = Column(
                              children: [
                                // รูปสินค้า
                                _SectionCard(
                                  icon: Icons.photo_outlined,
                                  iconColor: const Color(0xFF7B1FA2),
                                  title: 'รูปสินค้า',
                                  child: _ImagePickerWidget(
                                    imagePath: _imagePath,
                                    onPick: _pickImage,
                                    onRemove: _removeImage,
                                  ),
                                ),
                                const SizedBox(height: 16),

                                // ตั้งค่าสต๊อก
                                _SectionCard(
                                  icon: Icons.warehouse_outlined,
                                  iconColor: AppTheme.success,
                                  title: 'ตั้งค่าสต๊อก',
                                  child: Column(
                                    children: [
                                      _SwitchRow(
                                        label: 'ควบคุมสต๊อก',
                                        subLabel: 'ติดตามการเคลื่อนไหว',
                                        value: _isStockControl,
                                        activeColor: AppTheme.success,
                                        onChanged: (v) => setState(
                                            () => _isStockControl = v),
                                      ),
                                      if (_isStockControl) ...[
                                        const Divider(
                                            height: 16, color: AppTheme.border),
                                        _SwitchRow(
                                          label: 'อนุญาตติดลบ',
                                          subLabel: 'ขายได้แม้สต๊อกหมด',
                                          value: _allowNegativeStock,
                                          activeColor: Colors.orange,
                                          onChanged: (v) => setState(
                                              () => _allowNegativeStock = v),
                                        ),
                                      ],
                                    ],
                                  ),
                                ),
                              ],
                            );
                      if (isWide) {
                        return IntrinsicHeight(
                          child: Row(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Expanded(flex: 5, child: c1),
                              const SizedBox(width: 16),
                              Expanded(flex: 4, child: c2),
                              const SizedBox(width: 16),
                              Expanded(flex: 3, child: c3),
                            ],
                          ),
                        );
                      }
                      return Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          c1, const SizedBox(height: 16),
                          c2, const SizedBox(height: 16),
                          c3,
                        ],
                      );
                    }),
                  ],
                ),
              ),
            ),
          ),

          // ── Bottom Action Bar ─────────────────────────────────
          Builder(builder: (context) {
            final isDark = Theme.of(context).brightness == Brightness.dark;
            return Container(
            color: isDark ? AppTheme.darkTopBar : Colors.white,
            padding:
                const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                OutlinedButton(
                  onPressed:
                      _isLoading ? null : () => Navigator.pop(context),
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 24, vertical: 12),
                    side: const BorderSide(color: AppTheme.border),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8)),
                  ),
                  child: const Text('ยกเลิก',
                      style: TextStyle(color: AppTheme.textSub)),
                ),
                const SizedBox(width: 12),
                ElevatedButton.icon(
                  onPressed: _isLoading ? null : _handleSubmit,
                  icon: _isLoading
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                              strokeWidth: 2, color: Colors.white),
                        )
                      : const Icon(Icons.save_outlined, size: 18),
                  label: Text(isEdit ? 'บันทึก' : 'เพิ่มสินค้า',
                      style: const TextStyle(fontSize: 14)),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppTheme.primary,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(
                        horizontal: 24, vertical: 12),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8)),
                    elevation: 0,
                  ),
                ),
              ],
            ),
          );
          }),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Title Bar
// ─────────────────────────────────────────────────────────────────
class _TitleBar extends StatelessWidget {
  final bool isEdit;
  const _TitleBar({required this.isEdit});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      color: isDark ? AppTheme.darkTopBar : Colors.white,
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: AppTheme.primaryLight,
              borderRadius: BorderRadius.circular(8),
            ),
            child: const Icon(Icons.inventory_2_outlined,
                color: AppTheme.primary, size: 20),
          ),
          const SizedBox(width: 12),
          Text(
            isEdit ? 'แก้ไขสินค้า' : 'เพิ่มสินค้า',
            style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: isDark ? Colors.white : const Color(0xFF1A1A1A)),
          ),
          const Spacer(),
          if (Navigator.of(context).canPop())
            InkWell(
              onTap: () => Navigator.pop(context),
              borderRadius: BorderRadius.circular(6),
              child: Padding(
                padding: const EdgeInsets.all(4),
                child: Icon(Icons.close, size: 20,
                    color: isDark ? Colors.white54 : AppTheme.textSub),
              ),
            ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Barcode Field — พร้อมปุ่มสแกน
// ─────────────────────────────────────────────────────────────────
class _BarcodeField extends StatelessWidget {
  final TextEditingController controller;
  final bool enabled;
  final void Function(String) onScanned;

  const _BarcodeField({
    required this.controller,
    required this.enabled,
    required this.onScanned,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // ── ปุ่มสแกน (ขึ้นก่อน) ──────────────────────────────
        SizedBox(
          width: double.infinity,
          child: ElevatedButton.icon(
            onPressed: enabled
                ? () async {
                    await MobileScannerService.openContinuous(
                      context,
                      onScanned: (result) {
                        Navigator.of(context).pop();
                        onScanned(result.value);
                      },
                    );
                  }
                : null,
            icon: const Icon(Icons.qr_code_scanner, size: 18),
            label: const Text('สแกนบาร์โค้ด',
                style: TextStyle(fontSize: 13)),
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF1565C0),
              foregroundColor: Colors.white,
              padding:
                  const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8)),
              elevation: 0,
            ),
          ),
        ),
        const SizedBox(height: 8),

        // ── Text field บาร์โค้ด ──────────────────────────────
        TextFormField(
          controller: controller,
          enabled: enabled,
          style: const TextStyle(fontSize: 13),
          decoration: InputDecoration(
            labelText: 'บาร์โค้ด',
            labelStyle: const TextStyle(fontSize: 13, color: AppTheme.textSub),
            hintText: 'กรอกหรือสแกนบาร์โค้ด',
            hintStyle: const TextStyle(fontSize: 12, color: AppTheme.textSub),
            prefixIcon: const Icon(Icons.qr_code, size: 17, color: AppTheme.textSub),
            suffixIcon: IconButton(
              icon: const Icon(Icons.qr_code_scanner,
                  size: 18, color: AppTheme.info),
              tooltip: 'สแกน',
              onPressed: enabled
                  ? () async {
                      await MobileScannerService.openContinuous(
                        context,
                        onScanned: (result) {
                          Navigator.of(context).pop();
                          onScanned(result.value);
                        },
                      );
                    }
                  : null,
            ),
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
            border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: AppTheme.border)),
            enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: AppTheme.border)),
            focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide:
                    const BorderSide(color: AppTheme.primary, width: 1.5)),
            filled: true,
            fillColor: Theme.of(context).brightness == Brightness.dark
                ? AppTheme.darkElement
                : Colors.white,
          ),
        ),
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Product Code Field — แสดง badge "อัตโนมัติ" + ปุ่ม generate
// ─────────────────────────────────────────────────────────────────
class _ProductCodeField extends StatelessWidget {
  final TextEditingController controller;
  final bool isEdit;
  final bool isAutoGenerated;
  final bool enabled;
  final VoidCallback onAutoGenerate;
  final VoidCallback onManualEdit;

  const _ProductCodeField({
    required this.controller,
    required this.isEdit,
    required this.isAutoGenerated,
    required this.enabled,
    required this.onAutoGenerate,
    required this.onManualEdit,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Label row — มี badge + ปุ่ม
        Row(
          children: [
            const Text('รหัสสินค้า *',
                style: TextStyle(fontSize: 12, color: AppTheme.textSub)),
            const SizedBox(width: 6),
            if (isAutoGenerated)
              Container(
                padding: const EdgeInsets.symmetric(
                    horizontal: 7, vertical: 2),
                decoration: BoxDecoration(
                  color: AppTheme.successContainer,
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: const Color(0xFF81C784)),
                ),
                child: const Text('สร้างอัตโนมัติ',
                    style: TextStyle(
                        fontSize: 10,
                        color: AppTheme.success,
                        fontWeight: FontWeight.w600)),
              ),
            const Spacer(),
            // ปุ่ม generate (เฉพาะ create mode)
            if (!isEdit)
              InkWell(
                onTap: onAutoGenerate,
                borderRadius: BorderRadius.circular(6),
                child: Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: AppTheme.primaryLight,
                    borderRadius: BorderRadius.circular(6),
                    border: Border.all(
                        color: AppTheme.primary.withValues(alpha: 0.3)),
                  ),
                  child: const Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.auto_awesome,
                          size: 12, color: AppTheme.primary),
                      SizedBox(width: 4),
                      Text('สร้างรหัส',
                          style: TextStyle(
                              fontSize: 11,
                              color: AppTheme.primary,
                              fontWeight: FontWeight.w500)),
                    ],
                  ),
                ),
              ),
          ],
        ),
        const SizedBox(height: 4),

        // TextField
        TextFormField(
          controller: controller,
          enabled: enabled,
          style: const TextStyle(fontSize: 13),
          onChanged: (_) => onManualEdit(),
          validator: (v) =>
              (v == null || v.isEmpty) ? 'กรุณากรอกรหัสสินค้า' : null,
          decoration: InputDecoration(
            hintText: 'เช่น PRD-250321-001 หรือเท่ากับบาร์โค้ด',
            hintStyle: const TextStyle(fontSize: 12, color: AppTheme.textSub),
            prefixIcon:
                const Icon(Icons.tag, size: 17, color: AppTheme.textSub),
            contentPadding: const EdgeInsets.symmetric(
                horizontal: 12, vertical: 12),
            border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: AppTheme.border)),
            enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: BorderSide(
                    color: isAutoGenerated
                        ? const Color(0xFF81C784)
                        : AppTheme.border)),
            focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide:
                    const BorderSide(color: AppTheme.primary, width: 1.5)),
            errorBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
                borderSide: const BorderSide(color: Colors.red)),
            filled: true,
            fillColor: isAutoGenerated
                ? AppTheme.successContainer.withValues(alpha: 0.4)
                : Colors.white,
          ),
        ),
        // Helper text
        Padding(
          padding: const EdgeInsets.only(top: 4, left: 2),
          child: Text(
            isEdit
                ? 'รหัสสินค้า (ไม่แนะนำให้เปลี่ยน)'
                : 'ปล่อยว่างระบบจะสร้างให้อัตโนมัติ หรือใช้บาร์โค้ดเป็นรหัส',
            style: const TextStyle(fontSize: 10, color: AppTheme.textSub),
          ),
        ),
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Price Row — 2 fields side by side
// ─────────────────────────────────────────────────────────────────
class _PriceRow extends StatelessWidget {
  final TextEditingController c1;
  final String l1;
  final String h1; // helper text field 1
  final TextEditingController c2;
  final String l2;
  final String h2; // helper text field 2
  final bool enabled;

  const _PriceRow({
    required this.c1,
    required this.l1,
    required this.h1,
    required this.c2,
    required this.l2,
    required this.h2,
    required this.enabled,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: _FormField(
            controller: c1,
            label: '$l1 — $h1',
            icon: Icons.attach_money,
            keyboardType: TextInputType.number,
            prefixText: '฿',
            enabled: enabled,
          ),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: _FormField(
            controller: c2,
            label: '$l2 — $h2',
            icon: Icons.attach_money,
            keyboardType: TextInputType.number,
            prefixText: '฿',
            enabled: enabled,
          ),
        ),
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Switch Row
// ─────────────────────────────────────────────────────────────────
class _SwitchRow extends StatelessWidget {
  final String label;
  final String subLabel;
  final bool value;
  final Color activeColor;
  final ValueChanged<bool> onChanged;

  const _SwitchRow({
    required this.label,
    required this.subLabel,
    required this.value,
    required this.activeColor,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(label,
                  style: TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.w500,
                      color: Theme.of(context).brightness == Brightness.dark
                          ? Colors.white
                          : Colors.black87)),
              Text(subLabel,
                  style: TextStyle(
                      fontSize: 11,
                      color: Theme.of(context).brightness == Brightness.dark
                          ? Colors.white54
                          : AppTheme.textSub)),
            ],
          ),
        ),
        Switch(
          value: value,
          onChanged: onChanged,
          activeThumbColor: activeColor,
          materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
        ),
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Section Card
// ─────────────────────────────────────────────────────────────────
class _SectionCard extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final String title;
  final Widget child;

  const _SectionCard({
    required this.icon,
    required this.iconColor,
    required this.title,
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      decoration: BoxDecoration(
        color: isDark ? AppTheme.darkCard : Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
            color: isDark ? Colors.white12 : AppTheme.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: BoxDecoration(
              color: isDark ? AppTheme.darkElement : AppTheme.headerBg,
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(12),
                topRight: Radius.circular(12),
              ),
              border: Border(
                  bottom: BorderSide(
                      color: isDark ? Colors.white12 : AppTheme.border)),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(6),
                  decoration: BoxDecoration(
                    color: iconColor.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: Icon(icon, size: 15, color: iconColor),
                ),
                const SizedBox(width: 8),
                Text(title,
                    style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                        color: iconColor)),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(16),
            child: child,
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Generic Form Field
// ─────────────────────────────────────────────────────────────────
class _FormField extends StatelessWidget {
  final TextEditingController controller;
  final String label;
  final IconData icon;
  final bool required;
  final bool enabled;
  final TextInputType? keyboardType;
  final String? prefixText;
  final String? helperText;
  final String? Function(String?)? validator;

  const _FormField({
    required this.controller,
    required this.label,
    required this.icon,
    this.required = false,
    this.enabled = true,
    this.keyboardType,
    this.prefixText,
    this.helperText,
    this.validator,
  });

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      controller: controller,
      enabled: enabled,
      keyboardType: keyboardType,
      maxLines: 1,
      validator: validator,
      style: TextStyle(
        fontSize: 13,
        color: Theme.of(context).brightness == Brightness.dark
            ? Colors.white
            : Colors.black87,
      ),
      decoration: InputDecoration(
        labelText: required ? '$label *' : label,
        labelStyle: TextStyle(
            fontSize: 13,
            color: Theme.of(context).brightness == Brightness.dark
                ? Colors.white60
                : AppTheme.textSub),
        helperText: helperText,
        helperStyle: TextStyle(
            fontSize: 11,
            color: Theme.of(context).brightness == Brightness.dark
                ? Colors.white54
                : AppTheme.textSub),
        prefixIcon: Icon(icon, size: 17,
            color: Theme.of(context).brightness == Brightness.dark
                ? Colors.white54
                : AppTheme.textSub),
        prefixText: prefixText,
        prefixStyle: TextStyle(
            fontSize: 13,
            color: Theme.of(context).brightness == Brightness.dark
                ? Colors.white70
                : AppTheme.textSub),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
        border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: BorderSide(
                color: Theme.of(context).brightness == Brightness.dark
                    ? Colors.white24
                    : AppTheme.border)),
        enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: BorderSide(
                color: Theme.of(context).brightness == Brightness.dark
                    ? Colors.white24
                    : AppTheme.border)),
        focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: AppTheme.primary, width: 1.5)),
        errorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Colors.red)),
        filled: true,
        fillColor: enabled
            ? (Theme.of(context).brightness == Brightness.dark
                ? AppTheme.darkElement
                : Colors.white)
            : (Theme.of(context).brightness == Brightness.dark
                ? AppTheme.darkCard
                : const Color(0xFFF5F5F5)),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// Image Picker Widget
// ─────────────────────────────────────────────────────────────────
class _ImagePickerWidget extends StatelessWidget {
  final String? imagePath;
  final VoidCallback onPick;
  final VoidCallback onRemove;

  const _ImagePickerWidget({
    required this.imagePath,
    required this.onPick,
    required this.onRemove,
  });

  @override
  Widget build(BuildContext context) {
    final hasImage   = imagePath != null && imagePath!.isNotEmpty;
    final file       = hasImage ? File(imagePath!) : null;
    final fileExists = file != null && file.existsSync();

    return Column(
      children: [
        // Preview
        GestureDetector(
          onTap: onPick,
          child: Container(
            width: double.infinity,
            height: 120,
            decoration: BoxDecoration(
              color: hasImage && fileExists
                  ? AppTheme.primaryLight
                  : Colors.grey[400],
              borderRadius: BorderRadius.circular(10),
              border: Border.all(
                color: hasImage && fileExists
                    ? AppTheme.primary.withValues(alpha: 0.4)
                    : Colors.grey[400]!,
                width: hasImage && fileExists ? 1.5 : 1,
              ),
            ),
            child: hasImage && fileExists
                ? ClipRRect(
                    borderRadius: BorderRadius.circular(9),
                    child: Image.file(file,
                        fit: BoxFit.cover,
                        errorBuilder: (_, e, s) => _placeholder()),
                  )
                : _placeholder(),
          ),
        ),
        const SizedBox(height: 10),

        // Buttons
        Row(
          children: [
            Expanded(
              child: ElevatedButton.icon(
                onPressed: onPick,
                icon: const Icon(Icons.photo_library_outlined, size: 15),
                label: Text(hasImage ? 'เปลี่ยนรูป' : 'เลือกรูป',
                    style: const TextStyle(fontSize: 12)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.primary,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8)),
                  elevation: 0,
                ),
              ),
            ),
            if (hasImage) ...[
              const SizedBox(width: 8),
              OutlinedButton(
                onPressed: onRemove,
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(
                      vertical: 8, horizontal: 12),
                  side: const BorderSide(color: Colors.red),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8)),
                ),
                child: const Icon(Icons.delete_outline,
                    size: 16, color: Colors.red),
              ),
            ],
          ],
        ),
        const SizedBox(height: 6),
        const Text('JPG, PNG, WEBP',
            style: TextStyle(fontSize: 10, color: AppTheme.textSub)),
      ],
    );
  }

  Widget _placeholder() => const Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.add_photo_alternate_outlined,
              size: 32, color: Colors.white),
          SizedBox(height: 6),
          Text('กดเพื่อเลือกรูป',
              style: TextStyle(fontSize: 11, color: Colors.white)),
        ],
      );
}